/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

/**
 *
 * @author Gagandeep
 */
public class Dialog_ErrorHandler extends javax.swing.JDialog {

    /**
     * Creates new form Dialog_ErrorHandler
     */
    public Dialog_ErrorHandler(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        //recieveInfo("Please Complete All Entries!", 201);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textF_code = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textF_type = new javax.swing.JTextField();
        symbol = new javax.swing.JLabel();
        textF_stmt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textA_desc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textA_tips = new javax.swing.JTextArea();
        btn_ok = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        topBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SPA | Exception Handler");
        setMaximumSize(new java.awt.Dimension(400, 480));
        setPreferredSize(new java.awt.Dimension(400, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Code :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 120, 70, 20);

        textF_code.setEditable(false);
        textF_code.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_code.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(textF_code);
        textF_code.setBounds(130, 120, 220, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Type :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 160, 70, 20);

        textF_type.setEditable(false);
        textF_type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_type.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(textF_type);
        textF_type.setBounds(130, 160, 220, 20);

        symbol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/Alert.png"))); // NOI18N
        symbol.setPreferredSize(new java.awt.Dimension(29, 29));
        getContentPane().add(symbol);
        symbol.setBounds(40, 60, 29, 29);

        textF_stmt.setEditable(false);
        textF_stmt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textF_stmt.setForeground(new java.awt.Color(12, 120, 73));
        textF_stmt.setBorder(null);
        textF_stmt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textF_stmt.setOpaque(false);
        getContentPane().add(textF_stmt);
        textF_stmt.setBounds(90, 60, 260, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Discription :");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 200, 70, 20);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));

        textA_desc.setColumns(20);
        textA_desc.setEditable(false);
        textA_desc.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textA_desc.setRows(5);
        textA_desc.setText("An error was encountered while creating \nyour pdf file. Possible reasons are :\n• The path you have provided belongs to\n   an already existing pdf file. This file is\n   currently being used by another \n   program, thus it cannot be overridden.\n• The application is not able to create \n   file because a required privilede is \n   not held by the user.\n• Some of the contents used by this\n   application to create pdf file has been\n   found missing.");
        textA_desc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(textA_desc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 200, 220, 80);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tips :");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 305, 70, 20);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));

        textA_tips.setColumns(20);
        textA_tips.setEditable(false);
        textA_tips.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textA_tips.setRows(5);
        textA_tips.setText("• If you are trying to replace an already\n  existing pdf file, make sure that file is\n  not occupied by some another program.\n  If so, please close all applications and \n  then try again.\n• It may happen that you are unable to\n   create file because the user account\n   using which you have logged in to \n   your machine does not have \n   privileges to access the location you \n   have specified. Try using some other\n   location or login as an administrator.\n• If you have verified above two cases \n   and problem still exist, someone has\n   intentionally tempered the application\n   file structure. In such a case we\n  advice you to reinstall the application.");
        textA_tips.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(textA_tips);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 305, 220, 80);

        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/ok_1.png"))); // NOI18N
        btn_ok.setBorderPainted(false);
        btn_ok.setContentAreaFilled(false);
        btn_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ok.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/ok_3.png"))); // NOI18N
        btn_ok.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/ok_2.png"))); // NOI18N
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ok);
        btn_ok.setBounds(155, 410, 90, 31);

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Resgistration/exit_1.png"))); // NOI18N
        btn_exit.setBorderPainted(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Resgistration/exit_3.png"))); // NOI18N
        btn_exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Resgistration/exit_2.png"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(155, 410, 90, 31);

        topBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/exceptionHandler_topBar.png"))); // NOI18N
        getContentPane().add(topBar);
        topBar.setBounds(0, 0, 400, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:        
        dispose();
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        LogHandler log=new LogHandler();
        log.writeToLog(33);
        log.writeToLog(34);
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    //--------------------- MT METHOD -------------------------
    
    void recieveInfo(String m,int c[])
    {
        String tmp="";
        for(int i=0;i<6;i++)
        {
            tmp+=c[i];
        }
            
        textF_code.setText(tmp);
        getType(c);
        textF_stmt.setText(m);
        
        setDiscrip(c);
        
        
        
    }
    
    void setDiscrip(int c[])
    {
        int type=c[0];
        int err=c[1]*10+c[2];
        
        switch(type)
        {
            case 1 : {  //ERROR
                          switch(err)
                          {
                              case 01 : { 
                                           textA_desc.setText("An error occurred while reading \nregistration and configuration settings.\nThis is possibility because the \nregistration has either been illegally \nremoved from your system explicitly by \nexternal means or the registration has \nbeen corrupted. The application thus \ncannot proceed further and requires \nimmediate restart. \nPlease note that, this condition may be \nconsidered as an illegal act of \nmanipulating this application. If you are \naware of this act or yourself involved in \nint it, you may be penalized under law. ");
                                           textA_tips.setText("This is an unrecoverable error. You have\nto restart the application and register \nagain. However, your database file as \nwell as your backup remains untouched.\nIf your last database status showed no\nerrors, so while registration, you can\nsimply specify the DSN you have been\nusing till now. The application will\nautomatically pick up the database from\nthe point where it is supposed to be \nused again.");
                                        }break;
                                  
                              case 02 : { 
                                           textA_desc.setText("An error has occurred while creating \nbackup of your database because the \nworkbook being used as database has \neither been explicitly renamed, deleted\nor misplaced from the location where it\nis suppose to be present.This condition\nis due to an external operation by \nanother application or by a naïve user.");
                                           textA_tips.setText("To find the problem follow the following\nsteps : \n• Since the workbook is not available,\n   you must immediately navigate to the\n   path yourself, where the file is\n   supposed to be present. Check if it\n   has not been renamed. (If you don’t\n   know the path,  go to ODBC \n   connections from control panel, for \n   your DSN, get the path)\n• If the file is not present, look up your \n   harddisk if it has been moved to some\n   other location (If you remember file’s\n   name). Use search facility provided \n   by your operating system itself.\n   If you have found it, restore it to the\n   previous location, or you may change\n   your DSN setting by setting new path\n   of the workbook.\n• If you are still unable to resolve the \n   problem, let the application restart\n   itself. Once in the Main Menu, \n   go to ‘Settings’ and let yourself guided\n   by the ‘database connectivity and\n   recovery wizard’. Choose restore\n   option when asked. If you have\n   created a backup, it will be restored.");
                                        }break;
                                  
                              case 03 : { 
                                           textA_desc.setText("A major error has been detected while\nreading a record from your database. \nIt has been found that the database \nconnection link is broken and the \napplication is unable to proceed further.\nThere are various possibilities that may \nhave caused such kind of error :\n• Invalid DSN : Invalid DSN means that\n   the DSN you have provided either has\n   not been created or has been \n   changed to some other name.\n• Incompatible DSN : The workbook\n   attached to your DSN is either not an\n   excel file (Excel 97-2003 Workbook -\n   .xls) or the workbook itself is\n    corrupted. The workbook in such a\n    case has been intentionally tempered\n    by any external means (other than\n    by this application) or is not a\n    formatted workbook suitable for this \n    application.\n• Missing Workbook : The workbook \n   being used as database has either \n   been explicitly renamed, deleted or\n   misplaced from the location where it is\n   suppose to be present.This condition \n   is due to an external operation by\n   another application or by a naïve user.");
                                           textA_tips.setText("To overcome this error you must follow\nfollowing steps :\n• Firstly verify your DSN. Go to \n   'Control Panel' -> \n   'Administrative Tools' -> \n   'Data Sources (ODBC)' , select\n   'System DSN' tab and check whether\n    the DSN you are trying to connect \n    exist. If not create a new DSN and\n    remember its name. Use this name\n    when prompt for database\n    connectivity. If DSN is present, \n    carefully verify spelling. If DSN exist,\n    check its spelling. If spelling is correct,\n    follow next step.\n• In ‘System DSN’ tab make sure that\n   you have selected 'Driver do Microsoft\n   Excel (*.xls)'  and the selected excel \n   file is an 'Excel 97-2003 Workbook' \n   with extension .xls. Moreover this\n   workbook must be formatted suitable\n   for use by this application. If is so and\n   problem is not solved, check out next \n   step.\n• The third and the last possibility for\n   this error is, the workbook is missing.\n   It has either been renamed or deleted \n   or even misplaced from its location.\n   Try, searching you original file and \n    restore it its previous state.\nIf the problem still persist, go to \n‘Settings’ from Main Menu, tick \n‘Create new connection’ checkbox, and\nlet yourself guided by the ‘database \nconnectivity and recovery wizard’.");
                                        }break;
                                  
                              default : { 
                                           textA_desc.setText("Unknown Error Detected!\nCannot continue further!\nThe application will terminate now!");
                                           textA_tips.setText("Please inform the developing team \nabout this error.\nSend the error 'Code' and 'Type' \ndisplayed above along with your \nname and product key to:\nGagandeep Singh\ngagandeep.taurus91@gmail.com\n9717568636");
                                        }break;
                           }
                
                     }break;
                
            case 2 : {  //ALERT
                          switch(err)
                          {
                              case 01 : { 
                                           textA_desc.setText("One of the entries has been found\nincomplete or unselected.\nThe screen will not proceed further until\nyou complete all the required entries.");
                                           textA_tips.setText("• Make sure you have complete all the\n  necessary inputs.\n• Complete all text fields on screen if\n   present.\n• Make sure you have selected atleast \n   one radio button if you are in the \n   middle of analytic test.");
                                        }break;
                                  
                              case 02 : { 
                                           textA_desc.setText("Non-Integer values are not allowed for\nnput in text fields corresponding to \nPhone number, Mobile Number, Fax \nNumber. \nThe screen will not proceed further until\nyou enter correct integer values.");
                                           textA_tips.setText("• An integer value is necessary in these \n   fields. There is no alternative.\n• If you do not wish to enter any value,\n   use 0 instead.");
                                        }break;
                                  
                              case 03 : { 
                                           textA_desc.setText("Null or empty fields are not acceptable.  \nSuch fields must contain a value.\nThe screen will not proceed further until\nyou enter a value.");
                                           textA_tips.setText("• Do not leave any field empty. Use ‘0’ \n   to specify that you do not wish to \n   enter any value.\n• Take precautions when you enter \n   values in the cells of a table. Use enter\n   key every time you enter a new value \n   to override the previous one. If \n   forgotten, the previous value will be \n   readas current value, even if the new \n   value is visible to that cell. ");
                                        }break;
                                  
                              case 04 : { 
                                           textA_desc.setText("This error state indicates that the value \nentered in a field is logically invalid or \nincompatible.\nThe following are the possible condition \nand corresponding areas in the \napplication where this error can be \nobserved :\n• Login : Wrong password Entered.\n• Add New Record : While entering \n   values in table. Actuals being greater \n   than Expected or the condition \n   CT>P>L>S is not followed.\n• Mine Data : You have not selected a \n   row.");
                                           textA_tips.setText("To remove this error check following \npoints corresponding to the problem \narea :\n• Login : Enter correct password. This \n   password must match to the password\n   you have set during registration or \n   to the password that you have \n   changed later.\n• Add New Record : Make sure Actuals \n   are less than Expected or the condition\n   CT>P>L>S is satisfied.\n• Mine Data : Selected a row \n   corresponding to a record.");
                                        }break;
                                  
                              case 05 : { 
                                           textA_desc.setText("An error has occurred while creating \nbackup of currently running database. \nVarious possibilities are :\n• The database connection is broken i.e.\n   database is not connected connection.\n• Application is unable to create backup \n   file due to permission constraints by \n   the operating system i.e. the user \n   running this application does not have \n   rights to change the directory \n   structure due to which the application \n   is unable to create the directories itself\n   or is unable to copy paste the backup \n   file to the destination location.");
                                           textA_tips.setText("• Make sure database is connected. \n   Go to ‘View system state’ from Main \n   Menu. If database is not connected \n   check your DSN, check the existence \n   of your workbook, check that the \n   workbook connect is compatible.\n• Try to login as an administrator to your\n   machine and then run this application.");
                                        }break;
                                  
                              case 06 : { 
                                           textA_desc.setText("The DSN to which you are connected is \nset as ‘Read Only’. As a result the \napplication will not be able to write new \ndata. This condition is not an error to be \nprecise since database is compatible, \nconnected and readable, however this \nconstraint must be remove explicitly by \nthe user to enable write and update \noperations.");
                                           textA_tips.setText("To remove this constraint, Go to \n'Control Panel' -> \n'Administrative Tools' -> \n'Data Sources (ODBC)' , select \n'System DSN' tab, select the DSN you \nhave connected to this application and \nclick ‘Configure…’ button. From the new\nscreen that pops up, click ‘Option>>’ \nbutton. Under the driver section, untick \nthe Read Only checkbox. Click ‘Ok’ .");
                                        }break;
                                  
                              case 07 : { 
                                           textA_desc.setText("The application is unable to connect to \nthe database since the DSN you have \nprovided is Invalid. Here, Invalid means \nthat the DSN provided has not been \ncreated or has been changed to some \nother name. If you are currently proving\nthe DSN, perhaps you are typing wrong \nspelling.");
                                           textA_tips.setText("To overcome this problem, Go to\n 'Control Panel' -> \n'Administrative Tools' -> \n'Data Sources (ODBC)' , select \n'System DSN' tab and check whether the \nDSN you are trying to connect exist. If \nnot create a new DSN and remember its\nname. Use this name when prompt for\ndatabase connectivity.If DSN is present,\ncarefully verify the spelling.");
                                        }break;
                                  
                                  
                              case 8 : { 
                                           textA_desc.setText("It has been found that the DSN to which\nyou are currently connected or trying to\nconnect is incompatible i.e.it is either not\nan excel file (Excel 97-2003 Workbook -\n.xls) or the workbook itself is corrupted.\nThe workbook in such a case has been \nintentionally tempered by any external \nmeans (other than by this application) or\nis not a formatted workbook suitable for\nthis application. It may also happen that\nthe workbook has been deleted or \ndisplaced from the path where it was \nsupposed to be.");
                                           textA_tips.setText("Firstly, verify your DSN. Go to \n'Control Panel' ->\n'Administrative Tools' -> \n'Data Sources (ODBC)' , select \n'System DSN' tab and make sure that\nyou have selected 'Driver do Microsoft \nExcel (*.xls)' and the selected excel file\nis an 'Excel 97-2003 Workbook' with \nextension .xls. Moreover this workbook \nmust be formatted suitable for use by \nthis application.\nIf the problem still persist, go to\n‘Settings’ from Main Menu, tick \n‘Create new connection’ checkbox,\nand let yourself guided by the \n‘database connectivity and recovery\nwizard’.");
                                        }break;
                                  
                              case 9 : { 
                                           textA_desc.setText("An error was encountered while creating \nyour pdf file. Possible reasons are :\n• The path you have provided belongs to\n   an already existing pdf file. This file is\n   currently being used by another \n   program, thus it cannot be overridden.\n• The application is not able to create \n   file because a required privilede is \n   not held by the user.\n• Some of the contents used by this\n   application to create pdf file has been\n   found missing.");
                                           textA_tips.setText("• If you are trying to replace an already\n  existing pdf file, make sure that file is\n  not occupied by some another program.\n  If so, please close all applications and \n  then try again.\n• It may happen that you are unable to\n   create file because the user account\n   using which you have logged in to \n   your machine does not have \n   privileges to access the location you \n   have specified. Try using some other\n   location or login as an administrator.\n• If you have verified above two cases \n   and problem still exist, someone has\n   intentionally tempered the application\n   file structure. In such a case we\n  advice you to reinstall the application.");
                                        }break;
                                  
                              default : { 
                                           textA_desc.setText("Unknown Error Detected!");
                                           textA_tips.setText("Please inform the developing team \nabout this error.\nSend the error 'Code' and 'Type' \ndisplayed above along with your \nname and product key to:\nGagandeep Singh\ngagandeep.taurus91@gmail.com\n9717568636");
                                        }break;
                          }
                     }break;
        }
        
    }
    
    private void getType(int c[])
    {
        if(c[0]==2)
        { 
            symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/Alert.png")));
            textF_type.setText("Alert"); 
            btn_ok.setVisible(true);
            btn_exit.setVisible(false);
        }
        else
        { 
            symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/Error.png")));
            textF_type.setText("Error"); 
            btn_ok.setVisible(false);
            btn_exit.setVisible(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_ErrorHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_ErrorHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_ErrorHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_ErrorHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Dialog_ErrorHandler dialog = new Dialog_ErrorHandler(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel symbol;
    private javax.swing.JTextArea textA_desc;
    private javax.swing.JTextArea textA_tips;
    private javax.swing.JTextField textF_code;
    private javax.swing.JTextField textF_stmt;
    private javax.swing.JTextField textF_type;
    private javax.swing.JLabel topBar;
    // End of variables declaration//GEN-END:variables
}
