/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

import javax.swing.UIManager;

/**
 *
 * @author Gagandeep
 */
public class Dialog_diagnosResult extends javax.swing.JDialog {

    /**
     * Creates new form Dialog_diagnosResult
     */
    public Dialog_diagnosResult(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        try{
              UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
          }catch(Exception e)
          {  System.out.println("Windows isn't available"); }
        
        initComponents();
        
        this.setLocationRelativeTo(null);  //Open at center of screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_log = new javax.swing.JLabel();
        lbl_reg = new javax.swing.JLabel();
        lbl_db = new javax.swing.JLabel();
        lbl_bk = new javax.swing.JLabel();
        lbl_form = new javax.swing.JLabel();
        lbl_vir = new javax.swing.JLabel();
        log = new javax.swing.JLabel();
        reg = new javax.swing.JLabel();
        db = new javax.swing.JLabel();
        bk = new javax.swing.JLabel();
        format = new javax.swing.JLabel();
        vir = new javax.swing.JLabel();
        bg_topBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SPA | Loading Alert");
        setMaximumSize(new java.awt.Dimension(400, 280));
        setMinimumSize(new java.awt.Dimension(400, 280));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/ok_1.png"))); // NOI18N
        btn_ok.setBorderPainted(false);
        btn_ok.setContentAreaFilled(false);
        btn_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ok.setFocusPainted(false);
        btn_ok.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/ok_3.png"))); // NOI18N
        btn_ok.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/ok_2.png"))); // NOI18N
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ok);
        btn_ok.setBounds(150, 210, 90, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("The following are the errors found while loading the application :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(15, 55, 370, 15);

        lbl_log.setText("Application status :");
        getContentPane().add(lbl_log);
        lbl_log.setBounds(60, 85, 320, 16);

        lbl_reg.setText("Registration :");
        getContentPane().add(lbl_reg);
        lbl_reg.setBounds(60, 105, 320, 16);

        lbl_db.setText("Database :");
        getContentPane().add(lbl_db);
        lbl_db.setBounds(60, 125, 320, 16);

        lbl_bk.setText("Database BackUp :");
        getContentPane().add(lbl_bk);
        lbl_bk.setBounds(60, 145, 320, 16);

        lbl_form.setText("Format File :");
        getContentPane().add(lbl_form);
        lbl_form.setBounds(60, 165, 320, 16);

        lbl_vir.setText("Inbox :");
        getContentPane().add(lbl_vir);
        lbl_vir.setBounds(60, 185, 330, 16);

        log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png"))); // NOI18N
        getContentPane().add(log);
        log.setBounds(32, 85, 19, 15);

        reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png"))); // NOI18N
        getContentPane().add(reg);
        reg.setBounds(32, 105, 19, 15);

        db.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png"))); // NOI18N
        getContentPane().add(db);
        db.setBounds(32, 125, 19, 15);

        bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png"))); // NOI18N
        getContentPane().add(bk);
        bk.setBounds(32, 145, 19, 15);

        format.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png"))); // NOI18N
        getContentPane().add(format);
        format.setBounds(32, 165, 19, 15);

        vir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png"))); // NOI18N
        getContentPane().add(vir);
        vir.setBounds(32, 185, 19, 15);

        bg_topBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/lodResult_topBar.png"))); // NOI18N
        getContentPane().add(bg_topBar);
        bg_topBar.setBounds(0, 0, 400, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_okActionPerformed

    void getStates(Diagnostic d)
    {
        if(d.logFlag==-1)
        {
            log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_error.png")));
            lbl_log.setText( lbl_log.getText()+" Corrupted");
        }else if(d.logFlag==32 || d.logFlag==33)
        {
            log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_alert.png")));
            lbl_log.setText("One of the process was not completed during last run");
        }else if(d.logFlag==31 || d.logFlag==0)
        {
            log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_alert.png")));
            lbl_log.setText("Application was not closed properly during last run");
        }else
        {
            log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png")));
            lbl_log.setText( lbl_log.getText()+" Ok");
        }
        
        if(d.configFlag==0)
        {
            reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_alert.png")));
            lbl_reg.setText( lbl_reg.getText()+" Corrupted");
        }else
        {
            reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png")));
            lbl_reg.setText( lbl_reg.getText()+" Done");
        }
        
        
        if(d.dbFlag<1)
        {
            db.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_error.png")));
            lbl_db.setText( lbl_db.getText()+" Not Connected");
        }else
        {
            db.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png")));
            lbl_db.setText( lbl_db.getText()+" Connected");
        }
        
        
        if(d.backupFlag==0)
        {
            bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_alert.png")));
            lbl_bk.setText( lbl_bk.getText()+" Not Found / Not created yet");
        }else
        {
            bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png")));
            lbl_bk.setText( lbl_bk.getText()+" Found");
        }
        
        
        if(d.formateFlag==0)
        {
            format.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_alert.png")));
            lbl_form.setText( lbl_form.getText()+" Not Found. This file is a part of installation.");
        }else
        {
            format.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png")));
            lbl_form.setText( lbl_form.getText()+" Present");
        }
        
        
        if(d.virtualFlag>0)
        {
            vir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png")));
            lbl_vir.setText( lbl_vir.getText()+" "+d.virtualFlag+" Records Found! Please save them into the database!");
        }else
        {
            vir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/bullet_ok.png")));
            lbl_vir.setText( lbl_vir.getText()+" No Records Found");
        }
        
        
        
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_diagnosResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_diagnosResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_diagnosResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_diagnosResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Dialog_diagnosResult dialog = new Dialog_diagnosResult(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_topBar;
    private javax.swing.JLabel bk;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel db;
    private javax.swing.JLabel format;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_bk;
    private javax.swing.JLabel lbl_db;
    private javax.swing.JLabel lbl_form;
    private javax.swing.JLabel lbl_log;
    private javax.swing.JLabel lbl_reg;
    private javax.swing.JLabel lbl_vir;
    private javax.swing.JLabel log;
    private javax.swing.JLabel reg;
    private javax.swing.JLabel vir;
    // End of variables declaration//GEN-END:variables
}
