/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

/**
 *
 * @author Gagandeep
 */
public class Dialog_About extends javax.swing.JDialog {

    /**
     * Creates new form Dialog_About
     */
    public Dialog_About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textA_SPA = new javax.swing.JTextArea();
        lbl_name = new javax.swing.JLabel();
        lbl_cmp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textA_java = new javax.swing.JTextArea();
        textA_names = new javax.swing.JTextArea();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SPA | About");
        setMinimumSize(new java.awt.Dimension(500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        textA_SPA.setColumns(20);
        textA_SPA.setEditable(false);
        textA_SPA.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textA_SPA.setRows(5);
        textA_SPA.setText("      Based on sales analysis technique formulated by Harmeet Singh Bahra, SPA - Sales Process  \nAnalyzer is a sales management tool that enables you to identify weak areas in your sales process \n                    and have more qualified prospects, leads and more sales conversions.");
        textA_SPA.setOpaque(false);
        getContentPane().add(textA_SPA);
        textA_SPA.setBounds(10, 225, 480, 50);

        lbl_name.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_name);
        lbl_name.setBounds(10, 291, 200, 16);

        lbl_cmp.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_cmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_cmp);
        lbl_cmp.setBounds(10, 307, 200, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registered to :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 275, 200, 16);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("© 2012 United Avenir Engineers | singh.gagan144@gmail.com | 9717568636");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 205, 480, 15);

        textA_java.setColumns(20);
        textA_java.setEditable(false);
        textA_java.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textA_java.setRows(5);
        textA_java.setText("                  A Java Technology Product\n                  Programming Environment :\n                         NetBeans IDE 7.1\n                  Java SE Development Kit 6");
        textA_java.setBorder(null);
        textA_java.setOpaque(false);
        getContentPane().add(textA_java);
        textA_java.setBounds(260, 275, 230, 60);

        textA_names.setColumns(20);
        textA_names.setEditable(false);
        textA_names.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textA_names.setRows(5);
        textA_names.setText("     Analysis Technique by : Harmeet Singh Bahra ( harmeetakaharry@gmail.com | 9717155311 )\n                                                                 Programming Team :\n                                Gagandeep Singh (singh.gagan144@gmail.com | 9717568636 )\n                                  Hargeet Kaur Bhatia ( raavibhatia@yahoo.in | 9350511201 )\n                      Amanpreet Singh Chauhan ( armaan.chauhans@gmail.com | 9910494991 )");
        textA_names.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textA_names.setOpaque(false);
        getContentPane().add(textA_names);
        textA_names.setBounds(8, 340, 480, 75);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/About_Bg.png"))); // NOI18N
        bg.setPreferredSize(new java.awt.Dimension(502, 430));
        getContentPane().add(bg);
        bg.setBounds(0, 0, 500, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Dialog_About dialog = new Dialog_About(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    void getData(String nm, String cmp)
    {
        lbl_name.setText(nm);
        lbl_cmp.setText(cmp);       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_cmp;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextArea textA_SPA;
    private javax.swing.JTextArea textA_java;
    private javax.swing.JTextArea textA_names;
    // End of variables declaration//GEN-END:variables
}
