/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

import javax.swing.UIManager;

/**
 *
 * @author Gagandeep
 */
public class Dialog_reg_child extends javax.swing.JDialog {

    /**
     * Creates new form Dialog_reg_child
     */
    LogHandler log=new LogHandler();
    int code=0;
    
    public Dialog_reg_child(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        try{
              UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
          }catch(Exception e)
          {  System.out.println("Windows isn't available"); }
        
        initComponents();
        
        this.setLocationRelativeTo(null);  //Open at center of screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ok = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        textA_msg = new javax.swing.JTextArea();
        symbol = new javax.swing.JLabel();
        bg_topBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SPA");
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/ok_1.png"))); // NOI18N
        btn_ok.setBorderPainted(false);
        btn_ok.setContentAreaFilled(false);
        btn_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ok.setFocusPainted(false);
        btn_ok.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/ok_3.png"))); // NOI18N
        btn_ok.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/ok_2.png"))); // NOI18N
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ok);
        btn_ok.setBounds(155, 135, 90, 31);

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Resgistration/exit_1.png"))); // NOI18N
        btn_exit.setBorderPainted(false);
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.setFocusPainted(false);
        btn_exit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Resgistration/exit_3.png"))); // NOI18N
        btn_exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Resgistration/exit_2.png"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(155, 135, 90, 31);

        textA_msg.setColumns(20);
        textA_msg.setEditable(false);
        textA_msg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textA_msg.setRows(5);
        textA_msg.setText("\n");
        textA_msg.setBorder(null);
        textA_msg.setOpaque(false);
        getContentPane().add(textA_msg);
        textA_msg.setBounds(130, 50, 240, 70);

        symbol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/alert.png"))); // NOI18N
        symbol.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(symbol);
        symbol.setBounds(30, 50, 80, 70);

        bg_topBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/dailog_top_bar.png"))); // NOI18N
        getContentPane().add(bg_topBar);
        bg_topBar.setBounds(0, 0, 400, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        
        if(code==1)
        { log.writeToLog(31); }
        else
        { log.writeToLog(33); }    
        log.writeToLog(34);
        System.exit(0);

    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btn_okActionPerformed

    void getMessage(String m, int c)
    {
        code=c;
        textA_msg.setText(m);
        
        if(c==2)
        { symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/done.png"))); 
          btn_exit.setVisible(false);
          btn_ok.setVisible(true);
        }
        else if(c==1)
        { symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/done.png"))); 
          btn_exit.setVisible(true);
          btn_ok.setVisible(false);
        }
        else if(c==0)
        { symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/alert.png"))); 
          btn_exit.setVisible(false);
          btn_ok.setVisible(true);
        }
        else
        { symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/error.png"))); 
          btn_exit.setVisible(true);
          btn_ok.setVisible(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */  
          
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_reg_child.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_reg_child.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_reg_child.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_reg_child.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Dialog_reg_child dialog = new Dialog_reg_child(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_topBar;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel symbol;
    private javax.swing.JTextArea textA_msg;
    // End of variables declaration//GEN-END:variables
}
