/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

/**
 *
 * @author Acer
 */
public class PanelPhase1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelPhase1
     */
          
    /*
    String p1_cNm;
    String p1_cmpNm;
    String p1_d;
    String p1_prod;
    long p1_phNo;    
    * 
    */
    
    public PanelPhase1() {
        initComponents();              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_cName = new javax.swing.JLabel();
        label_cmpName = new javax.swing.JLabel();
        label_desig = new javax.swing.JLabel();
        label_product = new javax.swing.JLabel();
        label_phNo = new javax.swing.JLabel();
        textF_cName = new javax.swing.JTextField();
        textF_cmpName = new javax.swing.JTextField();
        textF_desig = new javax.swing.JTextField();
        textF_product = new javax.swing.JTextField();
        textF_phNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textF_add = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textF_mob = new javax.swing.JTextField();
        textF_fax = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textF_emailOff = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textF_emailPer = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        label_cName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_cName.setText("Client Name :");
        add(label_cName);
        label_cName.setBounds(300, 130, 110, 20);

        label_cmpName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_cmpName.setText("Company     :");
        add(label_cmpName);
        label_cmpName.setBounds(300, 190, 110, 20);

        label_desig.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_desig.setText("Designation :");
        add(label_desig);
        label_desig.setBounds(300, 220, 110, 20);

        label_product.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_product.setText("Product        :");
        add(label_product);
        label_product.setBounds(300, 250, 110, 20);

        label_phNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_phNo.setText("Phone No.   :");
        add(label_phNo);
        label_phNo.setBounds(300, 280, 110, 20);

        textF_cName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        add(textF_cName);
        textF_cName.setBounds(410, 130, 190, 20);

        textF_cmpName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        add(textF_cmpName);
        textF_cmpName.setBounds(410, 190, 190, 20);

        textF_desig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        add(textF_desig);
        textF_desig.setBounds(410, 220, 190, 20);

        textF_product.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        add(textF_product);
        textF_product.setBounds(410, 250, 190, 20);

        textF_phNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        add(textF_phNo);
        textF_phNo.setBounds(410, 280, 190, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Address :");
        add(jLabel1);
        jLabel1.setBounds(300, 160, 110, 20);

        textF_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        add(textF_add);
        textF_add.setBounds(410, 160, 190, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mobile No. :");
        add(jLabel2);
        jLabel2.setBounds(300, 310, 110, 20);

        textF_mob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        add(textF_mob);
        textF_mob.setBounds(410, 310, 190, 20);

        textF_fax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        add(textF_fax);
        textF_fax.setBounds(410, 340, 190, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Fax No. :");
        add(jLabel3);
        jLabel3.setBounds(300, 340, 110, 20);

        textF_emailOff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        add(textF_emailOff);
        textF_emailOff.setBounds(410, 370, 190, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Official eMail ID:");
        add(jLabel4);
        jLabel4.setBounds(300, 370, 110, 20);

        textF_emailPer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        add(textF_emailPer);
        textF_emailPer.setBounds(410, 400, 190, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Personal eMail ID :");
        add(jLabel5);
        jLabel5.setBounds(300, 400, 110, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Please Enter Your Details :");
        add(jLabel6);
        jLabel6.setBounds(340, 90, 220, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(12, 120, 73));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/PersInfo.png"))); // NOI18N
        jLabel7.setText(" Personal Information");
        add(jLabel7);
        jLabel7.setBounds(305, 15, 290, 60);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    public boolean assignAllData(Record ref,int currId)
    {
        ref.recordID=currId;
        System.out.println("Currently using ID : "+ref.recordID);  //delete
        
        String errMsg="Please complete all Entries!";
        String strTmp="";
        long tmp;
        long max;
        
        try
        {
            strTmp=textF_cName.getText();
            if(strTmp.equals(""))
                { throw new Exception(errMsg); }
            else
                { ref.clientName=strTmp; }
            
            strTmp=textF_add.getText();
            if(strTmp.equals(""))
                { throw new Exception(errMsg); }
            else
                { ref.address=strTmp; }            
            
            strTmp=textF_cmpName.getText();
            if(strTmp.equals(""))
                { throw new Exception(errMsg); }
            else
                { ref.cmpName=strTmp; }

            strTmp=textF_desig.getText();
            if(strTmp.equals(""))
                { throw new Exception(errMsg); }
            else
                { ref.desig=strTmp; }
            
            strTmp=textF_product.getText();
            if(strTmp.equals(""))
                { throw new Exception(errMsg); }
            else
                { ref.product=strTmp; }
                  
            
            tmp=Long.parseLong(textF_phNo.getText());                      
            max=Long.parseLong("9999999999");
            if(tmp>=max)
            {  throw new Exception("Invalid Phone Number!"); }
            ref.phNo=tmp;
            
            tmp=Long.parseLong(textF_mob.getText());                        
            if(tmp>=max)
            {  throw new Exception("Invalid Mobile Number!"); }
            ref.mobileNo=tmp;
                        
            tmp=Long.parseLong(textF_fax.getText());            
            max=Long.parseLong("9999999999999");
            if(tmp>=max)
            {  throw new Exception("Invalid Fax Number!"); }
            ref.faxNo=tmp;  
            
            int flag=0;
            strTmp=textF_emailOff.getText();
            if(strTmp.equals(""))
            { ref.email_off=""; }
            else
            { ref.email_off=strTmp; flag=1;}
            
            
            strTmp=textF_emailPer.getText();
            if(strTmp.equals(""))
            { ref.email_per=""; }
            else
            { ref.email_per=strTmp; flag=1; }
            
            
            if(flag==0)
            { throw new Exception(errMsg); }
            
            
        }catch(NumberFormatException e)
        {
            //System.out.println(e.getMessage());
            SPA.panelController("Integer value required for Phone, Mobile and Fax Number!", new int[]{2,0,2,3,1,0});            
            return(false);
        }catch(Exception e)
        {   
            //System.out.println(e.getMessage());       
            SPA.panelController(e.getMessage(), new int[]{2,0,1,3,1,0});            
            return(false);
        }
            
        SPA.panelController("", new int[]{0,0,0,3,1,0});            
        return(true);        
    }
    
    void resetPanel()
    {
        textF_cName.setText("");
        textF_add.setText("");
        textF_cmpName.setText("");    
        textF_desig.setText("");    
        textF_product.setText("");    
        textF_phNo.setText("");    
        textF_mob.setText("");    
        textF_fax.setText("");    
        textF_emailOff.setText("");    
        textF_emailPer.setText("");    
    }
    
    void loadPanel(Record r)
    {
        textF_cName.setText(r.clientName);
        textF_add.setText(r.address);
        textF_cmpName.setText(r.cmpName); 
        textF_desig.setText(r.desig);    
        textF_product.setText(r.product);    
        textF_phNo.setText(String.valueOf(r.phNo));    
        textF_mob.setText(String.valueOf(r.mobileNo));    
        textF_fax.setText(String.valueOf(r.faxNo));    
        textF_emailOff.setText(String.valueOf(r.email_off));    
        textF_emailPer.setText(String.valueOf(r.email_per)); 
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label_cName;
    private javax.swing.JLabel label_cmpName;
    private javax.swing.JLabel label_desig;
    private javax.swing.JLabel label_phNo;
    private javax.swing.JLabel label_product;
    private javax.swing.JTextField textF_add;
    private javax.swing.JTextField textF_cName;
    private javax.swing.JTextField textF_cmpName;
    private javax.swing.JTextField textF_desig;
    private javax.swing.JTextField textF_emailOff;
    private javax.swing.JTextField textF_emailPer;
    private javax.swing.JTextField textF_fax;
    private javax.swing.JTextField textF_mob;
    private javax.swing.JTextField textF_phNo;
    private javax.swing.JTextField textF_product;
    // End of variables declaration//GEN-END:variables
}
