package salesPackage;

public class PanelPhase4 extends javax.swing.JPanel {

    /** Creates new form PanelPhase4 */
    public PanelPhase4() {
        initComponents();
    }
    public int p4_r1;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGp_p4_q1 = new javax.swing.ButtonGroup();
        heading_p4 = new javax.swing.JLabel();
        label_p4_q1 = new javax.swing.JLabel();
        radio_p4_q1_1 = new javax.swing.JRadioButton();
        radio_p4_q1_2 = new javax.swing.JRadioButton();
        radio_p4_q1_3 = new javax.swing.JRadioButton();
        radio_p4_q1_4 = new javax.swing.JRadioButton();
        radio_p4_q1_5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        diagram = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(900, 540));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        heading_p4.setFont(new java.awt.Font("Tahoma", 1, 16));
        heading_p4.setForeground(new java.awt.Color(12, 120, 73));
        heading_p4.setText("4. Generate Qualified Leads:");
        add(heading_p4);
        heading_p4.setBounds(30, 220, 280, 20);

        label_p4_q1.setFont(new java.awt.Font("Tahoma", 1, 12));
        label_p4_q1.setText("Q1) Have you broken down your product / solution/ services offerings into well scripted RTC (Reason to Call)?  For Example: Advantages for ");
        label_p4_q1.setToolTipText("");
        label_p4_q1.setMaximumSize(new java.awt.Dimension(922, 10));
        label_p4_q1.setMinimumSize(new java.awt.Dimension(922, 10));
        label_p4_q1.setPreferredSize(new java.awt.Dimension(922, 10));
        add(label_p4_q1);
        label_p4_q1.setBounds(30, 270, 860, 20);
        label_p4_q1.getAccessibleContext().setAccessibleName("Q1)Have you broken down your product / solution/ services offerings into well scripted RTC (Reason to Call)? \n For Example: Advantages for Strategic Buyer, Economic Buyer & Technical Buyer.");

        btnGp_p4_q1.add(radio_p4_q1_1);
        radio_p4_q1_1.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p4_q1_1.setText("Yes, we have well scripted RTC for all our products, offerings, solutions and services for Strategic, Technical and Economic Buyer.");
        radio_p4_q1_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q1_1.setOpaque(false);
        radio_p4_q1_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q1_1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q1_1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q1_1ActionPerformed(evt);
            }
        });
        add(radio_p4_q1_1);
        radio_p4_q1_1.setBounds(80, 330, 740, 20);

        btnGp_p4_q1.add(radio_p4_q1_2);
        radio_p4_q1_2.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p4_q1_2.setText("Yes we have RTCs and EDMs however they are not well defined for Strategic, Economic and Technical Buyer.");
        radio_p4_q1_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q1_2.setOpaque(false);
        radio_p4_q1_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q1_2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q1_2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q1_2ActionPerformed(evt);
            }
        });
        add(radio_p4_q1_2);
        radio_p4_q1_2.setBounds(80, 355, 740, 20);

        btnGp_p4_q1.add(radio_p4_q1_3);
        radio_p4_q1_3.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p4_q1_3.setText("Yes, we have RTCs and EDMs however the calling is not script based.");
        radio_p4_q1_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q1_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q1_3.setOpaque(false);
        radio_p4_q1_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q1_3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q1_3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q1_3ActionPerformed(evt);
            }
        });
        add(radio_p4_q1_3);
        radio_p4_q1_3.setBounds(80, 380, 740, 20);

        btnGp_p4_q1.add(radio_p4_q1_4);
        radio_p4_q1_4.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p4_q1_4.setText("No we do not have RTCs and EDMs however our cold calling is based on email introductions.");
        radio_p4_q1_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q1_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q1_4.setOpaque(false);
        radio_p4_q1_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q1_4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q1_4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q1_4ActionPerformed(evt);
            }
        });
        add(radio_p4_q1_4);
        radio_p4_q1_4.setBounds(80, 405, 740, 20);

        btnGp_p4_q1.add(radio_p4_q1_5);
        radio_p4_q1_5.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p4_q1_5.setText("No we do not have RTCs and EDMs and our cold calling is random.  ");
        radio_p4_q1_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q1_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q1_5.setOpaque(false);
        radio_p4_q1_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q1_5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q1_5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q1_5ActionPerformed(evt);
            }
        });
        add(radio_p4_q1_5);
        radio_p4_q1_5.setBounds(80, 430, 740, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText(" Strategic Buyer, Economic Buyer & Technical Buyer.");
        add(jLabel1);
        jLabel1.setBounds(50, 290, 380, 15);

        diagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/SPDiag_4_1.gif"))); // NOI18N
        add(diagram);
        diagram.setBounds(155, 20, 590, 170);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void radio_p4_q1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q1_1ActionPerformed
        // TODO add your handling code here:
        p4_r1=1;
    }//GEN-LAST:event_radio_p4_q1_1ActionPerformed

    private void radio_p4_q1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q1_2ActionPerformed
        // TODO add your handling code here:
        p4_r1=2;
    }//GEN-LAST:event_radio_p4_q1_2ActionPerformed

    private void radio_p4_q1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q1_3ActionPerformed
        // TODO add your handling code here:
        p4_r1=3;
    }//GEN-LAST:event_radio_p4_q1_3ActionPerformed

    private void radio_p4_q1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q1_4ActionPerformed
        // TODO add your handling code here:
        p4_r1=4;
    }//GEN-LAST:event_radio_p4_q1_4ActionPerformed

    private void radio_p4_q1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q1_5ActionPerformed
        // TODO add your handling code here:
        p4_r1=5;
    }//GEN-LAST:event_radio_p4_q1_5ActionPerformed

    //----------------------- MyMethods-----------------------
    public boolean assignAllData(Record ref)
    {
        String errMsg="Please select an option!";                      
                
        try
        {
            if(p4_r1==0)                     
                { throw new Exception(errMsg); }
            else
                { 
                    ref.phase4[0]=p4_r1;
                }                                      
        }catch(Exception e)
        {
            //System.out.println(e.getMessage());
            SPA.panelController(e.getMessage(), new int[]{2,0,1,3,1,0});
            return(false);
        }
        
        SPA.panelController(null, new int[]{0,0,0,3,1,0});
        return(true);
    }
    
    void resetPanel()
    {
        p4_r1=0;
        btnGp_p4_q1.clearSelection();      
    }
    
    void loadPanel(Record r)
    {           
        p4_r1=r.phase4[0];        
        
        switch(r.phase4[0]) 
        {
            case 1 : radio_p4_q1_1.setSelected(true); break;
            case 2 : radio_p4_q1_2.setSelected(true); break;
            case 3 : radio_p4_q1_3.setSelected(true); break;
            case 4 : radio_p4_q1_4.setSelected(true); break;
            case 5 : radio_p4_q1_5.setSelected(true); break;            
        }       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup btnGp_p4_q1;
    private javax.swing.JLabel diagram;
    private javax.swing.JLabel heading_p4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_p4_q1;
    private javax.swing.JRadioButton radio_p4_q1_1;
    private javax.swing.JRadioButton radio_p4_q1_2;
    private javax.swing.JRadioButton radio_p4_q1_3;
    private javax.swing.JRadioButton radio_p4_q1_4;
    private javax.swing.JRadioButton radio_p4_q1_5;
    // End of variables declaration//GEN-END:variables
}
