package salesPackage;

public class PanelPhase4b extends javax.swing.JPanel {

    /** Creates new form PanelPhase4 */
    public PanelPhase4b() {
        initComponents();
    }
    public int p4_r2;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGp_p4_q2 = new javax.swing.ButtonGroup();
        label_p4_q2 = new javax.swing.JLabel();
        radio_p4_q2_1 = new javax.swing.JRadioButton();
        radio_p4_q2_2 = new javax.swing.JRadioButton();
        radio_p4_q2_3 = new javax.swing.JRadioButton();
        radio_p4_q2_4 = new javax.swing.JRadioButton();
        diagram = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(900, 540));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        label_p4_q2.setFont(new java.awt.Font("Tahoma", 1, 12));
        label_p4_q2.setText("Q2) Do you have and use a Reason to Call Calendar to get in touch with qualified prospect list? ");
        label_p4_q2.setMaximumSize(new java.awt.Dimension(455, 10));
        label_p4_q2.setMinimumSize(new java.awt.Dimension(455, 10));
        label_p4_q2.setPreferredSize(new java.awt.Dimension(455, 10));
        add(label_p4_q2);
        label_p4_q2.setBounds(50, 270, 640, 20);

        btnGp_p4_q2.add(radio_p4_q2_1);
        radio_p4_q2_1.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p4_q2_1.setText("Yes we have a quarterly reason to call calendar. ");
        radio_p4_q2_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q2_1.setOpaque(false);
        radio_p4_q2_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q2_1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q2_1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q2_1ActionPerformed(evt);
            }
        });
        add(radio_p4_q2_1);
        radio_p4_q2_1.setBounds(200, 355, 500, 20);

        btnGp_p4_q2.add(radio_p4_q2_2);
        radio_p4_q2_2.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p4_q2_2.setText("Yes we have a monthly reason to call calendar.");
        radio_p4_q2_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q2_2.setOpaque(false);
        radio_p4_q2_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q2_2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q2_2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q2_2ActionPerformed(evt);
            }
        });
        add(radio_p4_q2_2);
        radio_p4_q2_2.setBounds(200, 380, 500, 20);

        btnGp_p4_q2.add(radio_p4_q2_3);
        radio_p4_q2_3.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p4_q2_3.setText("No we do not have a monthly reason to call calendar but try to do it on weekly basis.");
        radio_p4_q2_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q2_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q2_3.setOpaque(false);
        radio_p4_q2_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q2_3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q2_3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q2_3ActionPerformed(evt);
            }
        });
        add(radio_p4_q2_3);
        radio_p4_q2_3.setBounds(200, 405, 500, 20);

        btnGp_p4_q2.add(radio_p4_q2_4);
        radio_p4_q2_4.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p4_q2_4.setText("Our calling team is not working according to reason to call calendar. ");
        radio_p4_q2_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q2_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q2_4.setOpaque(false);
        radio_p4_q2_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q2_4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q2_4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q2_4ActionPerformed(evt);
            }
        });
        add(radio_p4_q2_4);
        radio_p4_q2_4.setBounds(200, 430, 500, 20);

        diagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/SPDiag_4_2.gif"))); // NOI18N
        add(diagram);
        diagram.setBounds(155, 20, 590, 170);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void radio_p4_q2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q2_3ActionPerformed
        // TODO add your handling code here:
        p4_r2=3;
    }//GEN-LAST:event_radio_p4_q2_3ActionPerformed

    private void radio_p4_q2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q2_1ActionPerformed
        // TODO add your handling code here:
        p4_r2=1;
    }//GEN-LAST:event_radio_p4_q2_1ActionPerformed

    private void radio_p4_q2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q2_2ActionPerformed
        // TODO add your handling code here:
        p4_r2=2;
    }//GEN-LAST:event_radio_p4_q2_2ActionPerformed

    private void radio_p4_q2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q2_4ActionPerformed
        // TODO add your handling code here:
        p4_r2=4;
    }//GEN-LAST:event_radio_p4_q2_4ActionPerformed

    //----------------------- MyMethods-----------------------
    public boolean assignAllData(Record ref)
    {
        String errMsg="Please select an option!";                      
                
        try
        {
            if(p4_r2==0)                     
                { throw new Exception(errMsg); }
            else
                { ref.phase4[1]=p4_r2;  }                                      
        }catch(Exception e)
        {
            //System.out.println(e.getMessage());
            SPA.panelController(e.getMessage(), new int[]{2,0,1,3,1,0});
            return(false);
        }
        
        SPA.panelController(null, new int[]{0,0,0,3,1,0});
        return(true);
    }
    
    void resetPanel()
    {
        p4_r2=0;
        btnGp_p4_q2.clearSelection();      
    }
    
    void loadPanel(Record r)
    {           
        p4_r2=r.phase4[1];        
        
        switch(r.phase4[1]) 
        {
            case 1 : radio_p4_q2_1.setSelected(true); break;
            case 2 : radio_p4_q2_2.setSelected(true); break;
            case 3 : radio_p4_q2_3.setSelected(true); break;
            case 4 : radio_p4_q2_4.setSelected(true); break;            
        }       
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup btnGp_p4_q2;
    private javax.swing.JLabel diagram;
    private javax.swing.JLabel label_p4_q2;
    private javax.swing.JRadioButton radio_p4_q2_1;
    private javax.swing.JRadioButton radio_p4_q2_2;
    private javax.swing.JRadioButton radio_p4_q2_3;
    private javax.swing.JRadioButton radio_p4_q2_4;
    // End of variables declaration//GEN-END:variables
}
