/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

/**
 *
 * @author Gagandeep
 */
public class PanelSet_Ques extends javax.swing.JPanel {

    /**
     * Creates new form PanelSet_Ques
     */
    public PanelSet_Ques() {
        initComponents();
                
    }
    
    void ResetAllPanels()
    {
        panelPhase1.resetPanel();
        panelPhase2.resetPanel();
        panelPhase3a.resetPanel();
        panelPhase3b.resetPanel();
        panelPhase3c.resetPanel();
        panelPhase4.resetPanel();
        panelPhase4b.resetPanel();
        panelPhase4c.resetPanel();
        panelPhase4d.resetPanel();
        panelPhase4e.resetPanel();
        panelPhase5.resetPanel();
        panelPhase5b.resetPanel();
        panelPhase5c.resetPanel();
        panelPhase5d.resetPanel();
        
    }
    
    void loadAllPanels(Record r)
    {
        panelPhase1.loadPanel(r);
        panelPhase2.loadPanel(r);
        panelPhase3a.loadPanel(r);
        panelPhase3b.loadPanel(r);
        panelPhase3c.loadPanel(r);
        panelPhase4.loadPanel(r);
        panelPhase4b.loadPanel(r);
        panelPhase4c.loadPanel(r);
        panelPhase4d.loadPanel(r);
        panelPhase4e.loadPanel(r);
        panelPhase5.loadPanel(r);
        panelPhase5b.loadPanel(r);
        panelPhase5c.loadPanel(r);
        panelPhase5d.loadPanel(r);        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPhase1 = new salesPackage.PanelPhase1();
        panelPhase2_0 = new salesPackage.PanelPhase2_0();
        panelPhase2 = new salesPackage.PanelPhase2();
        panelOutput_graph1 = new salesPackage.PanelOutput_graph1();
        panelOutput_graph2 = new salesPackage.PanelOutput_graph2();
        panelPhase3 = new salesPackage.PanelPhase3();
        panelPhase3a = new salesPackage.PanelPhase3a();
        panelPhase3b = new salesPackage.PanelPhase3b();
        panelPhase3c = new salesPackage.PanelPhase3c();
        panelPhase4 = new salesPackage.PanelPhase4();
        panelPhase4b = new salesPackage.PanelPhase4b();
        panelPhase4c = new salesPackage.PanelPhase4c();
        panelPhase4d = new salesPackage.PanelPhase4d();
        panelPhase4e = new salesPackage.PanelPhase4e();
        panelPhase5 = new salesPackage.PanelPhase5();
        panelPhase5b = new salesPackage.PanelPhase5b();
        panelPhase5c = new salesPackage.PanelPhase5c();
        panelPhase5d = new salesPackage.PanelPhase5d();
        panelOutput_Gen = new salesPackage.PanelOutput_Gen();
        panelOutput_report = new salesPackage.PanelOutput_report();
        panel_Save = new salesPackage.Panel_Save();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 490));
        setLayout(new java.awt.CardLayout());

        panelPhase1.setName("phase1");
        add(panelPhase1, "phase1");
        add(panelPhase2_0, "phase2_0");
        panelPhase2_0.setName("phase2_0");
        panelPhase2_0.getAccessibleContext().setAccessibleName("");

        panelPhase2.setName("phase2");
        add(panelPhase2, "phase2");
        add(panelOutput_graph1, "output_graph1");
        panelOutput_graph1.setName("output_graph1");
        add(panelOutput_graph2, "output_graph2");
        panelOutput_graph2.setName("output_graph2");
        add(panelPhase3, "phase3");
        panelPhase3.setName("phase3");
        add(panelPhase3a, "phase3a");
        panelPhase3a.setName("phase3a");
        add(panelPhase3b, "phase3b");
        panelPhase3b.setName("phase3b");

        panelPhase3c.setName("phase3c");
        add(panelPhase3c, "phase3c");

        panelPhase4.setName("phase4");
        add(panelPhase4, "phase4");
        add(panelPhase4b, "phase4b");
        panelPhase4b.setName("phase4b");
        add(panelPhase4c, "phase4c");
        panelPhase4c.setName("phase4c");
        add(panelPhase4d, "phase4d");
        panelPhase4d.setName("phase4d");
        add(panelPhase4e, "phase4e");
        panelPhase4e.setName("phase4e");

        panelPhase5.setName("phase5");
        add(panelPhase5, "phase5");
        add(panelPhase5b, "phase5b");
        panelPhase5b.setName("phase5b");
        add(panelPhase5c, "phase5c");
        panelPhase5c.setName("phase5c");
        add(panelPhase5d, "phase5d");
        panelPhase5d.setName("phase5d");
        add(panelOutput_Gen, "output_gen");
        panelOutput_Gen.setName("output_gen");
        add(panelOutput_report, "output_report");
        panelOutput_report.setName("output_report");
        add(panel_Save, "save");
        panel_Save.setName("save");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public salesPackage.PanelOutput_Gen panelOutput_Gen;
    public salesPackage.PanelOutput_graph1 panelOutput_graph1;
    public salesPackage.PanelOutput_graph2 panelOutput_graph2;
    public salesPackage.PanelOutput_report panelOutput_report;
    public salesPackage.PanelPhase1 panelPhase1;
    public salesPackage.PanelPhase2 panelPhase2;
    private salesPackage.PanelPhase2_0 panelPhase2_0;
    private salesPackage.PanelPhase3 panelPhase3;
    public salesPackage.PanelPhase3a panelPhase3a;
    public salesPackage.PanelPhase3b panelPhase3b;
    public salesPackage.PanelPhase3c panelPhase3c;
    public salesPackage.PanelPhase4 panelPhase4;
    public salesPackage.PanelPhase4b panelPhase4b;
    public salesPackage.PanelPhase4c panelPhase4c;
    public salesPackage.PanelPhase4d panelPhase4d;
    public salesPackage.PanelPhase4e panelPhase4e;
    public salesPackage.PanelPhase5 panelPhase5;
    public salesPackage.PanelPhase5b panelPhase5b;
    public salesPackage.PanelPhase5c panelPhase5c;
    public salesPackage.PanelPhase5d panelPhase5d;
    public salesPackage.Panel_Save panel_Save;
    // End of variables declaration//GEN-END:variables
}
