package salesPackage;

public class PanelPhase3c extends javax.swing.JPanel {

    /**
     * Creates new form PanelPhase3
     */
    public int p3_r3;
    
    public PanelPhase3c() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGp_p3_q3 = new javax.swing.ButtonGroup();
        label_p3_q3 = new javax.swing.JLabel();
        radio_p3_q3_1 = new javax.swing.JRadioButton();
        radio_p3_q3_2 = new javax.swing.JRadioButton();
        radio_p3_q3_3 = new javax.swing.JRadioButton();
        radio_p3_q3_4 = new javax.swing.JRadioButton();
        diagram = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 540));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        label_p3_q3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_p3_q3.setText("Q3)Do you study the profile of the accounts deeply to decide sales strategy?  ");
        add(label_p3_q3);
        label_p3_q3.setBounds(40, 280, 540, 14);

        btnGp_p3_q3.add(radio_p3_q3_1);
        radio_p3_q3_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_p3_q3_1.setText("Yes, we study each account in our qualified account list based on it’s profile and make a annual sales engagement / strategy document.  ");
        radio_p3_q3_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p3_q3_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p3_q3_1.setOpaque(false);
        radio_p3_q3_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p3_q3_1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p3_q3_1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p3_q3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p3_q3_1ActionPerformed(evt);
            }
        });
        add(radio_p3_q3_1);
        radio_p3_q3_1.setBounds(55, 355, 790, 27);

        btnGp_p3_q3.add(radio_p3_q3_2);
        radio_p3_q3_2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_p3_q3_2.setText("Yes, we study each account in our qualified account list, however look for potential opportunity before making an engagement plan. ");
        radio_p3_q3_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p3_q3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p3_q3_2.setOpaque(false);
        radio_p3_q3_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p3_q3_2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p3_q3_2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p3_q3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p3_q3_2ActionPerformed(evt);
            }
        });
        add(radio_p3_q3_2);
        radio_p3_q3_2.setBounds(55, 380, 790, 27);

        btnGp_p3_q3.add(radio_p3_q3_3);
        radio_p3_q3_3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_p3_q3_3.setText("No, we do not make any annual sales engagement / strategy document and are dependent on our partners to help us find opportunities.");
        radio_p3_q3_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p3_q3_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p3_q3_3.setOpaque(false);
        radio_p3_q3_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p3_q3_3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p3_q3_3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p3_q3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p3_q3_3ActionPerformed(evt);
            }
        });
        add(radio_p3_q3_3);
        radio_p3_q3_3.setBounds(55, 405, 790, 27);

        btnGp_p3_q3.add(radio_p3_q3_4);
        radio_p3_q3_4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_p3_q3_4.setText("No, we do not make any annual sales engagement / strategy document and are opportunity oriented ");
        radio_p3_q3_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p3_q3_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p3_q3_4.setOpaque(false);
        radio_p3_q3_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p3_q3_4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p3_q3_4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p3_q3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p3_q3_4ActionPerformed(evt);
            }
        });
        add(radio_p3_q3_4);
        radio_p3_q3_4.setBounds(55, 430, 790, 27);

        diagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/SPDiag_3_3.gif"))); // NOI18N
        add(diagram);
        diagram.setBounds(155, 20, 590, 170);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void radio_p3_q3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p3_q3_1ActionPerformed
        // TODO add your handling code here:
        p3_r3=1;
    }//GEN-LAST:event_radio_p3_q3_1ActionPerformed

    private void radio_p3_q3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p3_q3_2ActionPerformed
        // TODO add your handling code here:
        p3_r3=2;
    }//GEN-LAST:event_radio_p3_q3_2ActionPerformed

    private void radio_p3_q3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p3_q3_3ActionPerformed
        // TODO add your handling code here:
        p3_r3=3;
    }//GEN-LAST:event_radio_p3_q3_3ActionPerformed

    private void radio_p3_q3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p3_q3_4ActionPerformed
        // TODO add your handling code here:
        p3_r3=4;
    }//GEN-LAST:event_radio_p3_q3_4ActionPerformed

    //----------------------- MyMethods-----------------------
    public boolean assignAllData(Record ref)
    {
        String errMsg="Please select an option!";                      
                
        try
        {
            if(p3_r3==0)                     
                { throw new Exception(errMsg); }
            else
                { 
                    ref.phase3[2]=p3_r3;                    
                }                                      
        }catch(Exception e)
        {
            //System.out.println(e.getMessage());
            SPA.panelController(e.getMessage(), new int[]{2,0,1,3,1,0});
            return(false);
        }
        
        SPA.panelController(null, new int[]{0,0,0,3,1,0});
        return(true);
    }
    
    void resetPanel()
    {
        p3_r3=0;
        btnGp_p3_q3.clearSelection();      
    }
    
    void loadPanel(Record r)
    {           
        p3_r3=r.phase3[2];        
        
        switch(r.phase3[2]) 
        {
            case 1 : radio_p3_q3_1.setSelected(true); break;
            case 2 : radio_p3_q3_2.setSelected(true); break;
            case 3 : radio_p3_q3_3.setSelected(true); break;
            case 4 : radio_p3_q3_4.setSelected(true); break;            
        }       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup btnGp_p3_q3;
    private javax.swing.JLabel diagram;
    private javax.swing.JLabel label_p3_q3;
    private javax.swing.JRadioButton radio_p3_q3_1;
    private javax.swing.JRadioButton radio_p3_q3_2;
    private javax.swing.JRadioButton radio_p3_q3_3;
    private javax.swing.JRadioButton radio_p3_q3_4;
    // End of variables declaration//GEN-END:variables
}
