/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPhase5.java
 *
 * Created on Feb 28, 2012, 10:02:45 PM
 */
package salesPackage;

/**
 *
 * @author user
 */
public class PanelPhase5b extends javax.swing.JPanel {

    /** Creates new form PanelPhase5 */
    public PanelPhase5b() {
        initComponents();
    }
    public int p5_r2;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Gp_p5_q2 = new javax.swing.ButtonGroup();
        label_p5_q2 = new javax.swing.JLabel();
        radio_p5_q2_1 = new javax.swing.JRadioButton();
        radio_p5_q2_2 = new javax.swing.JRadioButton();
        radio_p5_q2_3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        diagram = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 540));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        label_p5_q2.setFont(new java.awt.Font("Tahoma", 1, 12));
        label_p5_q2.setText("Q2) Do you have a relevant sales query form that the sales executives use to get customer feedback on presentations made to them? ");
        add(label_p5_q2);
        label_p5_q2.setBounds(30, 230, 860, 15);

        btn_Gp_p5_q2.add(radio_p5_q2_1);
        radio_p5_q2_1.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p5_q2_1.setText("Yes we have a relevant sales query form and it covers all these questions.");
        radio_p5_q2_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p5_q2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p5_q2_1.setOpaque(false);
        radio_p5_q2_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p5_q2_1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p5_q2_1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p5_q2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p5_q2_1ActionPerformed(evt);
            }
        });
        add(radio_p5_q2_1);
        radio_p5_q2_1.setBounds(130, 380, 640, 27);

        btn_Gp_p5_q2.add(radio_p5_q2_2);
        radio_p5_q2_2.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p5_q2_2.setText("Yes we have a relevant sales query form but it does not cover all these questions.");
        radio_p5_q2_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p5_q2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p5_q2_2.setOpaque(false);
        radio_p5_q2_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p5_q2_2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p5_q2_2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p5_q2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p5_q2_2ActionPerformed(evt);
            }
        });
        add(radio_p5_q2_2);
        radio_p5_q2_2.setBounds(130, 405, 640, 27);

        btn_Gp_p5_q2.add(radio_p5_q2_3);
        radio_p5_q2_3.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p5_q2_3.setText("No we do not have a relevant sales query form but would like to make one according to our line of business. ");
        radio_p5_q2_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p5_q2_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p5_q2_3.setOpaque(false);
        radio_p5_q2_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p5_q2_3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p5_q2_3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p5_q2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p5_q2_3ActionPerformed(evt);
            }
        });
        add(radio_p5_q2_3);
        radio_p5_q2_3.setBounds(130, 430, 640, 27);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("( yes / no)  (Strategic, Technical, Economic)  ");
        add(jLabel6);
        jLabel6.setBounds(50, 250, 310, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("• Why would they buy from us if they do? ");
        add(jLabel7);
        jLabel7.setBounds(60, 270, 350, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("• Why would they not buy from us?");
        add(jLabel8);
        jLabel8.setBounds(60, 290, 380, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("• What they expect from us to give the sales order to us? ");
        add(jLabel9);
        jLabel9.setBounds(60, 310, 410, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setText("• Are they convinced that this product/solution/service is right for them? ");
        add(jLabel10);
        jLabel10.setBounds(60, 330, 470, 15);

        diagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/SPDiag_5_2.gif"))); // NOI18N
        add(diagram);
        diagram.setBounds(155, 20, 590, 170);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void radio_p5_q2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p5_q2_1ActionPerformed
        // TODO add your handling code here:
        p5_r2=1;
    }//GEN-LAST:event_radio_p5_q2_1ActionPerformed

    private void radio_p5_q2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p5_q2_2ActionPerformed
        // TODO add your handling code here:
        p5_r2=2;
    }//GEN-LAST:event_radio_p5_q2_2ActionPerformed

    private void radio_p5_q2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p5_q2_3ActionPerformed
        // TODO add your handling code here:
        p5_r2=3;
    }//GEN-LAST:event_radio_p5_q2_3ActionPerformed

    //----------------------- MyMethods-----------------------
    public boolean assignAllData(Record ref)
    {
        String errMsg="Please select an option!";                      
                
        try
        {
            if(p5_r2==0)
                { throw new Exception(errMsg); }
            else
                { 
                   ref.phase5[1]=p5_r2;                    
                }                                      
        }catch(Exception e)
        {
            //System.out.println(e.getMessage());
            SPA.panelController(e.getMessage(), new int[]{2,0,1,3,1,0});
            return(false);
        }
        
        SPA.panelController(null, new int[]{0,0,0,3,1,0});
        return(true);
    }
    
    void resetPanel()
    {
        p5_r2=0;
        btn_Gp_p5_q2.clearSelection();      
    }
    
    void loadPanel(Record r)
    {           
        p5_r2=r.phase5[1];        
        
        switch(r.phase5[1]) 
        {
            case 1 : radio_p5_q2_1.setSelected(true); break;
            case 2 : radio_p5_q2_2.setSelected(true); break;
            case 3 : radio_p5_q2_3.setSelected(true); break;            
        }       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup btn_Gp_p5_q2;
    private javax.swing.JLabel diagram;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_p5_q2;
    private javax.swing.JRadioButton radio_p5_q2_1;
    private javax.swing.JRadioButton radio_p5_q2_2;
    private javax.swing.JRadioButton radio_p5_q2_3;
    // End of variables declaration//GEN-END:variables
}
