/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

/**
 *
 * @author Gagandeep
 */
public class PanelMascot extends javax.swing.JPanel {

    /**
     * Creates new form PanelMascot
     */
    public PanelMascot() {
        initComponents();
    }
    
    
    public void changeImage()
    {
        
        switch(SPA.stateWORD[0])
        {
            case 1 : {  mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/error.png"))); }
                      break;
                
            case 2 : {  mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/alert.png"))); }
                      break;
                
            default : {
                           if(SPA.stateWORD[3]==1 && SPA.stateWORD[4]==0 && SPA.stateWORD[5]==0 )
                           {
                               mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/getting_started.png")));
                           }
                           else if(SPA.stateWORD[3]==2 && SPA.stateWORD[4]==0 && SPA.stateWORD[5]==0 )
                           {
                               mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/login.png")));
                           }
                           else if(SPA.stateWORD[3]==3 && SPA.stateWORD[4]==0 && SPA.stateWORD[5]==0 )
                           {
                               mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/happy.png")));
                           }                           
                           else if(SPA.stateWORD[3]==3 && SPA.stateWORD[4]==1 && SPA.stateWORD[5]==0 )
                           {
                               mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/input.png")));
                           }
                           else if(SPA.stateWORD[3]==3 && SPA.stateWORD[4]==1 && SPA.stateWORD[5]==1 )
                           {
                               mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/output.png")));
                           }      
                           else if(SPA.stateWORD[3]==3 && SPA.stateWORD[4]==1 && SPA.stateWORD[5]==2 )
                           {
                               mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/save.png")));
                           }      
                           else if(SPA.stateWORD[3]==3 && SPA.stateWORD[4]==2 && SPA.stateWORD[5]==0 )
                           {
                               mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/mining.png")));
                           }
                           else if(SPA.stateWORD[3]==3 && SPA.stateWORD[4]==3 && SPA.stateWORD[5]==0 )
                           {
                               mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/diagnostic.png")));
                           }
                           else if(SPA.stateWORD[3]==3 && SPA.stateWORD[4]==4 && SPA.stateWORD[5]==0 )
                           {
                               mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/admin.png")));
                           }
                           
                      }
                
        } 
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mascot = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(126, 133));

        mascot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mascot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mascot/happy.png"))); // NOI18N
        mascot.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mascot)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mascot, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mascot;
    // End of variables declaration//GEN-END:variables
}
