/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPhase4b.java
 *
 * Created on Mar 1, 2012, 3:57:53 PM
 */
package salesPackage;

/**
 *
 * @author user
 */
public class PanelPhase4e extends javax.swing.JPanel {

    /** Creates new form PanelPhase4b */
    public PanelPhase4e() {
        initComponents();
    }
    public int p4_r5;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGp_p4_q5 = new javax.swing.ButtonGroup();
        label_p4_q5 = new javax.swing.JLabel();
        radio_p4_q5_1 = new javax.swing.JRadioButton();
        radio_p4_q5_2 = new javax.swing.JRadioButton();
        radio_p4_q5_3 = new javax.swing.JRadioButton();
        radio_p4_q5_4 = new javax.swing.JRadioButton();
        diagram = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 540));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        label_p4_q5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_p4_q5.setText("Q5) Does your sales team bring answers to 6 key aspects of qualified sales leads?");
        label_p4_q5.setMaximumSize(new java.awt.Dimension(392, 10));
        label_p4_q5.setMinimumSize(new java.awt.Dimension(392, 10));
        label_p4_q5.setPreferredSize(new java.awt.Dimension(392, 10));
        add(label_p4_q5);
        label_p4_q5.setBounds(40, 230, 510, 20);

        btnGp_p4_q5.add(radio_p4_q5_1);
        radio_p4_q5_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_p4_q5_1.setText("Yes our sales team members have answers to all 06 aspects of “qualified sales leads” for each account when we have a review.");
        radio_p4_q5_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q5_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q5_1.setOpaque(false);
        radio_p4_q5_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q5_1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q5_1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q5_1ActionPerformed(evt);
            }
        });
        add(radio_p4_q5_1);
        radio_p4_q5_1.setBounds(85, 355, 730, 20);

        btnGp_p4_q5.add(radio_p4_q5_2);
        radio_p4_q5_2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_p4_q5_2.setText("Yes our sales team members have some of the answers but they build the answers to all aspects on their own.");
        radio_p4_q5_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q5_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q5_2.setOpaque(false);
        radio_p4_q5_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q5_2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q5_2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q5_2ActionPerformed(evt);
            }
        });
        add(radio_p4_q5_2);
        radio_p4_q5_2.setBounds(85, 380, 730, 20);

        btnGp_p4_q5.add(radio_p4_q5_3);
        radio_p4_q5_3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_p4_q5_3.setText("No our sales team members do not have entire information at once, however we guide them to gather all information.");
        radio_p4_q5_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q5_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q5_3.setOpaque(false);
        radio_p4_q5_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q5_3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q5_3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q5_3ActionPerformed(evt);
            }
        });
        add(radio_p4_q5_3);
        radio_p4_q5_3.setBounds(85, 405, 730, 20);

        btnGp_p4_q5.add(radio_p4_q5_4);
        radio_p4_q5_4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_p4_q5_4.setText("No our sales team does not have this information and we do not guide them to get the same.");
        radio_p4_q5_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p4_q5_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p4_q5_4.setOpaque(false);
        radio_p4_q5_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p4_q5_4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p4_q5_4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p4_q5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p4_q5_4ActionPerformed(evt);
            }
        });
        add(radio_p4_q5_4);
        radio_p4_q5_4.setBounds(85, 430, 730, 20);

        diagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/SPDiag_4_5.gif"))); // NOI18N
        add(diagram);
        diagram.setBounds(155, 20, 590, 170);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("• Strategic Buyer:");
        add(jLabel1);
        jLabel1.setBounds(70, 260, 120, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("• Buying Decision Making Process");
        add(jLabel3);
        jLabel3.setBounds(280, 260, 220, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("• Possible Objections");
        add(jLabel2);
        jLabel2.setBounds(70, 280, 140, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("• Competition");
        add(jLabel4);
        jLabel4.setBounds(280, 280, 120, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("• Buying Decision Makers ");
        add(jLabel5);
        jLabel5.setBounds(70, 300, 160, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("• Budget");
        add(jLabel6);
        jLabel6.setBounds(280, 300, 90, 15);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void radio_p4_q5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q5_3ActionPerformed
        // TODO add your handling code here:
        p4_r5=3;
}//GEN-LAST:event_radio_p4_q5_3ActionPerformed

    private void radio_p4_q5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q5_1ActionPerformed
        // TODO add your handling code here:
        p4_r5=1;
    }//GEN-LAST:event_radio_p4_q5_1ActionPerformed

    private void radio_p4_q5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q5_2ActionPerformed
        // TODO add your handling code here:
        p4_r5=2;
    }//GEN-LAST:event_radio_p4_q5_2ActionPerformed

    private void radio_p4_q5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p4_q5_4ActionPerformed
        // TODO add your handling code here:
        p4_r5=4;
    }//GEN-LAST:event_radio_p4_q5_4ActionPerformed

    //----------------------- MyMethods-----------------------
    public boolean assignAllData(Record ref)
    {
        String errMsg="Please select an option!";                      
                
        try
        {
            if(p4_r5==0)                     
                { throw new Exception(errMsg); }
            else
                { ref.phase4[4]=p4_r5;  }                                      
        }catch(Exception e)
        {
            //System.out.println(e.getMessage());
            SPA.panelController(e.getMessage(), new int[]{2,0,1,3,1,0});
            return(false);
        }
        
        SPA.panelController(null, new int[]{0,0,0,3,1,0});
        return(true);
    }
    
    void resetPanel()
    {
        p4_r5=0;
        btnGp_p4_q5.clearSelection();      
    }
    
    void loadPanel(Record r)
    {           
        p4_r5=r.phase4[4];        
        
        switch(r.phase4[4]) 
        {
            case 1 : radio_p4_q5_1.setSelected(true); break;
            case 2 : radio_p4_q5_2.setSelected(true); break;
            case 3 : radio_p4_q5_3.setSelected(true); break;
            case 4 : radio_p4_q5_4.setSelected(true); break;            
        }       
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup btnGp_p4_q5;
    private javax.swing.JLabel diagram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel label_p4_q5;
    private javax.swing.JRadioButton radio_p4_q5_1;
    private javax.swing.JRadioButton radio_p4_q5_2;
    private javax.swing.JRadioButton radio_p4_q5_3;
    private javax.swing.JRadioButton radio_p4_q5_4;
    // End of variables declaration//GEN-END:variables
}
