/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Panel_login.java
 *
 * Created on Mar 3, 2012, 1:18:57 PM
 */
package salesPackage;

/**
 *
 * @author user
 */
public class Panel_login extends javax.swing.JPanel {

    /** Creates new form Panel_login */
    Configuration c_ref;
    LogHandler log = new LogHandler();
    
    public Panel_login() {
        initComponents();
        lb_invalid.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_add = new javax.swing.JButton();
        Label_login = new javax.swing.JLabel();
        Pswrd_field = new javax.swing.JPasswordField();
        Btn_login = new javax.swing.JButton();
        Btn_diagnosis = new javax.swing.JButton();
        lb_invalid = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        Btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/login/add_1.gif"))); // NOI18N
        Btn_add.setBorderPainted(false);
        Btn_add.setContentAreaFilled(false);
        Btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_add.setFocusPainted(false);
        Btn_add.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/login/add_3.gif"))); // NOI18N
        Btn_add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/login/add_2.gif"))); // NOI18N
        Btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_addActionPerformed(evt);
            }
        });
        add(Btn_add);
        Btn_add.setBounds(142, 150, 177, 157);

        Label_login.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_login.setForeground(new java.awt.Color(12, 120, 73));
        Label_login.setText("Password :");
        add(Label_login);
        Label_login.setBounds(380, 188, 80, 30);

        Pswrd_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pswrd_field.setForeground(new java.awt.Color(12, 120, 73));
        Pswrd_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pswrd_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 120, 73)));
        Pswrd_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pswrd_fieldActionPerformed(evt);
            }
        });
        add(Pswrd_field);
        Pswrd_field.setBounds(467, 190, 250, 30);

        Btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/login/btn_login_1.png"))); // NOI18N
        Btn_login.setBorderPainted(false);
        Btn_login.setContentAreaFilled(false);
        Btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_login.setFocusPainted(false);
        Btn_login.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/login/btn_login_3.png"))); // NOI18N
        Btn_login.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/login/btn_login_2.png"))); // NOI18N
        Btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_loginActionPerformed(evt);
            }
        });
        add(Btn_login);
        Btn_login.setBounds(630, 240, 90, 31);

        Btn_diagnosis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/login/status_1.gif"))); // NOI18N
        Btn_diagnosis.setBorderPainted(false);
        Btn_diagnosis.setContentAreaFilled(false);
        Btn_diagnosis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_diagnosis.setFocusPainted(false);
        Btn_diagnosis.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/login/status_3.gif"))); // NOI18N
        Btn_diagnosis.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/login/status_2.gif"))); // NOI18N
        Btn_diagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_diagnosisActionPerformed(evt);
            }
        });
        add(Btn_diagnosis);
        Btn_diagnosis.setBounds(142, 332, 618, 61);

        lb_invalid.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        lb_invalid.setForeground(new java.awt.Color(255, 0, 0));
        lb_invalid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_invalid.setText("Invalid password !");
        add(lb_invalid);
        lb_invalid.setBounds(470, 240, 140, 30);

        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/login/admin_border.png"))); // NOI18N
        add(admin);
        admin.setBounds(348, 143, 410, 164);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setFocusable(false);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_loginActionPerformed
        // TODO add your handling code here:
               chkPass();
    }//GEN-LAST:event_Btn_loginActionPerformed

    private void Btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_addActionPerformed
        // TODO add your handling code here:
        setVisible(false);                
        SPA.loggedIn=false;
        SPA.panelController(null, new int[]{0,0,0,3,1,0});
    }//GEN-LAST:event_Btn_addActionPerformed

    private void Btn_diagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_diagnosisActionPerformed
        // TODO add your handling code here:
        setVisible(false);                
        SPA.loggedIn=false;
        SPA.panelController(null, new int[]{0,0,0,3,3,0});
    }//GEN-LAST:event_Btn_diagnosisActionPerformed

    private void Pswrd_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pswrd_fieldActionPerformed
        // TODO add your handling code here:
        chkPass();
    }//GEN-LAST:event_Pswrd_fieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_add;
    private javax.swing.JButton Btn_diagnosis;
    private javax.swing.JButton Btn_login;
    private javax.swing.JLabel Label_login;
    private javax.swing.JPasswordField Pswrd_field;
    private javax.swing.JLabel admin;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel lb_invalid;
    // End of variables declaration//GEN-END:variables
    
    
    //my method
    void getReference(Configuration c)
    {
        c_ref= c;
    }
    
    void chkPass()
    {
        String temp;
        if(c_ref.readConfigFile(false)!=1)
        {
            SPA.panelController("Error Reading Registration!", new int[]{1,0,1,2,0,0});
        }
        
        try{
            temp=Pswrd_field.getText();
            if(temp.equals(c_ref.loginPass))
            {
                setVisible(false);                
                SPA.loggedIn=true;
                log.writeToLog(31);
                SPA.panelController(null, new int[]{0,0,0,3,0,0});
            }
            else
            {
                lb_invalid.setVisible(true);
                SPA.panelController("Invalid password!", new int[]{2,0,4,2,0,0});
                throw new Exception("invalid password");
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }

}
