package salesPackage;

import javax.swing.table.DefaultTableModel;

public class PanelInbox extends javax.swing.JPanel {

    /**
     * Creates new form PanelMineData
     */
    
    DatabaseHandler db=new DatabaseHandler();
    InboxHandler inbox=new InboxHandler();
    String list[];
    Record r=new Record();
    
    
    public PanelInbox() 
    {
        initComponents();
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        btn_transfer = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbl_totRecord = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/inbox/inbox_title.png"))); // NOI18N
        add(title);
        title.setBounds(316, 8, 267, 87);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("The records listed below have been found unattended. These records does not belong to your database, rather have been stored temporarly in files\nsince the user did not logged in or some problem occured while saving these records to database. We advise you to immediately transfer these \nrecord into your database.");
        jTextArea1.setOpaque(false);
        add(jTextArea1);
        jTextArea1.setBounds(32, 100, 836, 50);

        btn_transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/inbox/transfer_1.png"))); // NOI18N
        btn_transfer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 170, 73)));
        btn_transfer.setContentAreaFilled(false);
        btn_transfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_transfer.setFocusPainted(false);
        btn_transfer.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/inbox/transfer_3.png"))); // NOI18N
        btn_transfer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/inbox/transfer_2.png"))); // NOI18N
        btn_transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transferActionPerformed(evt);
            }
        });
        add(btn_transfer);
        btn_transfer.setBounds(760, 160, 110, 38);

        btn_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mine/view_1.png"))); // NOI18N
        btn_view.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 170, 73)));
        btn_view.setContentAreaFilled(false);
        btn_view.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_view.setFocusPainted(false);
        btn_view.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mine/view_3.png"))); // NOI18N
        btn_view.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mine/view_2.png"))); // NOI18N
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });
        add(btn_view);
        btn_view.setBounds(760, 210, 110, 38);

        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/inbox/del_1.png"))); // NOI18N
        btn_del.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 170, 73)));
        btn_del.setContentAreaFilled(false);
        btn_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_del.setFocusPainted(false);
        btn_del.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/inbox/del_3.png"))); // NOI18N
        btn_del.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/inbox/del_2.png"))); // NOI18N
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });
        add(btn_del);
        btn_del.setBounds(760, 260, 110, 38);

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mine/back_1.png"))); // NOI18N
        btn_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(12, 170, 73)));
        btn_back.setContentAreaFilled(false);
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.setFocusPainted(false);
        btn_back.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mine/back_3.png"))); // NOI18N
        btn_back.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Mine/back_2.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back);
        btn_back.setBounds(760, 320, 110, 38);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 138, 221), 2));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record Name", "Client Name", "Company Name", "Product", "Mobile No.", "EMail (Official)", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(32, 160, 700, 310);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 138, 221));
        jLabel2.setText("Total Pending Records Found : ");
        add(jLabel2);
        jLabel2.setBounds(32, 490, 210, 33);

        lbl_totRecord.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl_totRecord.setForeground(new java.awt.Color(0, 138, 221));
        lbl_totRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_totRecord.setText("0");
        add(lbl_totRecord);
        lbl_totRecord.setBounds(250, 490, 112, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/inbox/box.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(250, 490, 112, 33);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setFocusable(false);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transferActionPerformed
        // TODO add your handling code here:
        int row;
        String fileName="";
        
        try
        {
            row=jTable1.getSelectedRow();
            fileName=String.valueOf(jTable1.getModel().getValueAt(row,0));
            System.out.println("Transfring..."+fileName);
            
            r=inbox.getFromInbox(fileName);
            SPA.MAXRID++;
            r.recordID=SPA.MAXRID;
            
            db.insertInto(r);
            
            if(inbox.delRecord(fileName))            
            {
                System.out.println("File Deleted");
            }else
            {
                System.out.println("Error deleteing file");
            }
            
            refresh();
            
        }catch(Exception e)
        { System.out.println("Please Select a Record");  
          SPA.panelBubble.getState("Please Select a Record!", new int[]{2,0,4,3,2,0}); 
          //SPA.panelController("Please Select a Record!", new int[]{2,0,4,3,2,0}); 
        }
    }//GEN-LAST:event_btn_transferActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        int row;
        String fileName="";
        
        try
        {
            row=jTable1.getSelectedRow();
            fileName=String.valueOf(jTable1.getModel().getValueAt(row,0));
            System.out.println("View..."+fileName);
            r=inbox.getFromInbox(fileName);
            
            Dialog_ClientInfo d=new Dialog_ClientInfo(null, true);
            d.showInfo(r);
            d.setVisible(true);
            
            
        }catch(Exception e)
        { System.out.println("Please Select a Record"); 
          SPA.panelBubble.getState("Please Select a Record!", new int[]{2,0,4,3,2,0}); 
        }
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        
        SPA.panelController(null, new int[]{0,0,0,3,0,0});        
                
        //Remove all rows
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        for( int i = model.getRowCount() - 1; i >= 0; i-- )
        {   
            model.removeRow(i);
        }
        
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        int row;
        String fileName="";
        
        try
        {
            row=jTable1.getSelectedRow();
            fileName=String.valueOf(jTable1.getModel().getValueAt(row,0));
            System.out.println("deleting..."+fileName);
            inbox.delRecord(fileName);   
            
            refresh();
            
        }catch(Exception e)
        { System.out.println("Please Select a Record"); 
          SPA.panelBubble.getState("Please Select a Record!", new int[]{2,0,4,3,2,0}); 
        }
    }//GEN-LAST:event_btn_delActionPerformed

    
    //---------------MY Method----------------------
    
    private void refresh()
    {
        list=inbox.getList();
        SPA.DIAGNOSE.virtualFlag=inbox.NoOfRecords;
        lbl_totRecord.setText(String.valueOf(inbox.NoOfRecords));
        
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();  
        for( int i = model.getRowCount() - 1; i >= 0; i-- )
        {   
            model.removeRow(i);
        }
        
        for(int i=0;i<list.length;i++)
        {            
            r=inbox.getFromInbox(list[i]);    
            if(r!=null)
            { 
                model.insertRow(jTable1.getRowCount(), new Object[]{list[i], r.clientName, r.cmpName, r.product, r.mobileNo, r.email_off, r.date});      
            }
            
        }
    }
    
    void getReference(DatabaseHandler d)
    {
        db=d;
        refresh();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_transfer;
    private javax.swing.JButton btn_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_totRecord;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
