package salesPackage;

public class PanelOutput_graph1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelOutput_graph1
     */
    
    //StrageticData s = new StrageticData(); 
    
    public PanelOutput_graph1() {
        initComponents();        
        
        //----------Delete
        //s.initializeTempData();
        //s.processAllData();
        
        //showOutput(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lt_c1 = new javax.swing.JLabel();
        lt_c2 = new javax.swing.JLabel();
        lt_c3 = new javax.swing.JLabel();
        textA_client = new javax.swing.JTextArea();
        lt_s1 = new javax.swing.JLabel();
        lt_s2 = new javax.swing.JLabel();
        lt_s3 = new javax.swing.JLabel();
        textA_sales = new javax.swing.JTextArea();
        grph1a_exp1 = new javax.swing.JLabel();
        grph1a_act1 = new javax.swing.JLabel();
        grph1a_act2 = new javax.swing.JLabel();
        grph1a_exp2 = new javax.swing.JLabel();
        grph1a_act3 = new javax.swing.JLabel();
        grph1a_exp3 = new javax.swing.JLabel();
        grph1a_v1 = new javax.swing.JLabel();
        grph1a_v2 = new javax.swing.JLabel();
        grph1a_v3 = new javax.swing.JLabel();
        grph1a_v4 = new javax.swing.JLabel();
        grph1a_v5 = new javax.swing.JLabel();
        grph1a_y1 = new javax.swing.JLabel();
        grph1a_y2 = new javax.swing.JLabel();
        grph1a_y3 = new javax.swing.JLabel();
        graph1a_bg = new javax.swing.JLabel();
        grph1b_exp1 = new javax.swing.JLabel();
        grph1b_act1 = new javax.swing.JLabel();
        grph1b_act2 = new javax.swing.JLabel();
        grph1b_exp2 = new javax.swing.JLabel();
        grph1b_act3 = new javax.swing.JLabel();
        grph1b_exp3 = new javax.swing.JLabel();
        grph1b_v1 = new javax.swing.JLabel();
        grph1b_v2 = new javax.swing.JLabel();
        grph1b_v3 = new javax.swing.JLabel();
        grph1b_v4 = new javax.swing.JLabel();
        grph1b_v5 = new javax.swing.JLabel();
        grph1b_y1 = new javax.swing.JLabel();
        grph1b_y2 = new javax.swing.JLabel();
        grph1b_y3 = new javax.swing.JLabel();
        graph1b_bg = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        lt_c1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lt_c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); // NOI18N
        add(lt_c1);
        lt_c1.setBounds(139, 122, 25, 25);

        lt_c2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lt_c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); // NOI18N
        add(lt_c2);
        lt_c2.setBounds(232, 122, 25, 25);

        lt_c3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lt_c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); // NOI18N
        add(lt_c3);
        lt_c3.setBounds(325, 122, 25, 25);

        textA_client.setColumns(20);
        textA_client.setEditable(false);
        textA_client.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textA_client.setRows(5);
        textA_client.setText("Your company is facing alot of challenges in Sales Process Management.\nWe highly recommend you to take analytic test to identify weak areas\nand take immediate corrective actions for considerable improvement \nand conversions.");
        textA_client.setOpaque(false);
        add(textA_client);
        textA_client.setBounds(36, 400, 393, 70);

        lt_s1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lt_s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); // NOI18N
        add(lt_s1);
        lt_s1.setBounds(575, 122, 25, 25);

        lt_s2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lt_s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); // NOI18N
        add(lt_s2);
        lt_s2.setBounds(668, 122, 25, 25);

        lt_s3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lt_s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); // NOI18N
        add(lt_s3);
        lt_s3.setBounds(761, 122, 25, 25);

        textA_sales.setColumns(20);
        textA_sales.setEditable(false);
        textA_sales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textA_sales.setRows(5);
        textA_sales.setText("Your company is facing alot of challenges in Sales Process Management.\nWe highly recommend you to take analytic test to identify weak areas\nand take immediate corrective actions for considerable improvement \nand conversions.");
        textA_sales.setOpaque(false);
        add(textA_sales);
        textA_sales.setBounds(472, 400, 393, 70);

        grph1a_exp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/P_bar.gif"))); // NOI18N
        add(grph1a_exp1);
        grph1a_exp1.setBounds(311, 156, 26, 154);

        grph1a_act1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/L_bar.gif"))); // NOI18N
        add(grph1a_act1);
        grph1a_act1.setBounds(338, 156, 26, 154);

        grph1a_act2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/L_bar.gif"))); // NOI18N
        add(grph1a_act2);
        grph1a_act2.setBounds(245, 156, 26, 154);

        grph1a_exp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/P_bar.gif"))); // NOI18N
        add(grph1a_exp2);
        grph1a_exp2.setBounds(218, 156, 26, 154);

        grph1a_act3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/L_bar.gif"))); // NOI18N
        add(grph1a_act3);
        grph1a_act3.setBounds(152, 156, 26, 154);

        grph1a_exp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/P_bar.gif"))); // NOI18N
        add(grph1a_exp3);
        grph1a_exp3.setBounds(125, 156, 26, 154);

        grph1a_v1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grph1a_v1.setText("---");
        add(grph1a_v1);
        grph1a_v1.setBounds(40, 273, 45, 14);

        grph1a_v2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grph1a_v2.setText("---");
        add(grph1a_v2);
        grph1a_v2.setBounds(40, 242, 45, 14);

        grph1a_v3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grph1a_v3.setText("---");
        add(grph1a_v3);
        grph1a_v3.setBounds(40, 211, 45, 14);

        grph1a_v4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grph1a_v4.setText("---");
        add(grph1a_v4);
        grph1a_v4.setBounds(40, 180, 45, 14);

        grph1a_v5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grph1a_v5.setText("---");
        add(grph1a_v5);
        grph1a_v5.setBounds(40, 149, 45, 14);

        grph1a_y1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grph1a_y1.setText("---");
        add(grph1a_y1);
        grph1a_y1.setBounds(323, 320, 34, 14);

        grph1a_y2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grph1a_y2.setText("---");
        add(grph1a_y2);
        grph1a_y2.setBounds(228, 320, 34, 14);

        grph1a_y3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grph1a_y3.setText("---");
        add(grph1a_y3);
        grph1a_y3.setBounds(135, 320, 34, 14);

        graph1a_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Graph1a_bg.gif"))); // NOI18N
        add(graph1a_bg);
        graph1a_bg.setBounds(36, 71, 393, 309);

        grph1b_exp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/exp_sal_Bar.gif"))); // NOI18N
        add(grph1b_exp1);
        grph1b_exp1.setBounds(747, 155, 26, 154);

        grph1b_act1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/S_bar.gif"))); // NOI18N
        add(grph1b_act1);
        grph1b_act1.setBounds(774, 155, 26, 154);

        grph1b_act2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/S_bar.gif"))); // NOI18N
        add(grph1b_act2);
        grph1b_act2.setBounds(681, 155, 26, 154);

        grph1b_exp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/exp_sal_Bar.gif"))); // NOI18N
        add(grph1b_exp2);
        grph1b_exp2.setBounds(654, 155, 26, 154);

        grph1b_act3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/S_bar.gif"))); // NOI18N
        add(grph1b_act3);
        grph1b_act3.setBounds(588, 155, 26, 154);

        grph1b_exp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/exp_sal_Bar.gif"))); // NOI18N
        add(grph1b_exp3);
        grph1b_exp3.setBounds(561, 155, 26, 154);

        grph1b_v1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grph1b_v1.setText("---");
        add(grph1b_v1);
        grph1b_v1.setBounds(476, 273, 45, 14);

        grph1b_v2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grph1b_v2.setText("---");
        add(grph1b_v2);
        grph1b_v2.setBounds(476, 242, 45, 14);

        grph1b_v3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grph1b_v3.setText("---");
        add(grph1b_v3);
        grph1b_v3.setBounds(476, 211, 45, 14);

        grph1b_v4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grph1b_v4.setText("---");
        add(grph1b_v4);
        grph1b_v4.setBounds(476, 180, 45, 14);

        grph1b_v5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grph1b_v5.setText("---");
        add(grph1b_v5);
        grph1b_v5.setBounds(476, 149, 45, 14);

        grph1b_y1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grph1b_y1.setText("---");
        add(grph1b_y1);
        grph1b_y1.setBounds(760, 320, 34, 14);

        grph1b_y2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grph1b_y2.setText("---");
        add(grph1b_y2);
        grph1b_y2.setBounds(660, 320, 34, 14);

        grph1b_y3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grph1b_y3.setText("---");
        add(grph1b_y3);
        grph1b_y3.setBounds(570, 320, 34, 14);

        graph1b_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Graph1b_bg.gif"))); // NOI18N
        add(graph1b_bg);
        graph1b_bg.setBounds(472, 71, 393, 309);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    //-------------My METHODS-----------------
    void showOutput(StrageticData ref)
    {
        double h;        
        int y;   
        int tmp;        
        
        //Graph a - CLIENTS
        int max_g1a=ref.r.phase2a[0][1];        
        
        for(int i=0;i<3;i++)
        { 
                if(ref.r.phase2a[i][1]>max_g1a)
                { 
                   max_g1a=ref.r.phase2a[i][1];
                }
                        
        }
        
        grph1a_v5.setText(String.valueOf(max_g1a));
        tmp=(int)(max_g1a*0.8);
        grph1a_v4.setText(String.valueOf(tmp));
        tmp=(int)(max_g1a*0.6);
        grph1a_v3.setText(String.valueOf(tmp));
        tmp=(int)(max_g1a*0.4);
        grph1a_v2.setText(String.valueOf(tmp));
        tmp=(int)(max_g1a*0.2);
        grph1a_v1.setText(String.valueOf(tmp));
        
        
        grph1a_y1.setText(String.valueOf(ref.r.phase2a[0][0]));
        
        h=ref.r.phase2a[0][1];
        h=(double)(h/max_g1a)*154;
        y=156+(154-(int)h);         
        grph1a_exp1.setBounds(311, y, 26, ((int)h) );        
        
        h=ref.r.phase2a[0][2];
        h=(double)(h/max_g1a)*154;        
        y=156+(154-(int)h); 
        grph1a_act1.setBounds(338, y, 26, ((int)h) );
        
        
        grph1a_y2.setText(String.valueOf(ref.r.phase2a[1][0]));
        
        h=ref.r.phase2a[1][1];
        h=(double)(h/max_g1a)*154;
        y=156+(154-(int)h);         
        grph1a_exp2.setBounds(218, y, 26, ((int)h) );        
        
        h=ref.r.phase2a[1][2];
        h=(double)(h/max_g1a)*154;        
        y=156+(154-(int)h); 
        grph1a_act2.setBounds(245, y, 26, ((int)h) );
        
        
        grph1a_y3.setText(String.valueOf(ref.r.phase2a[2][0]));
        
        h=ref.r.phase2a[2][1];
        h=(double)(h/max_g1a)*154;
        y=156+(154-(int)h);         
        grph1a_exp3.setBounds(125, y, 26, ((int)h) );        
        
        h=ref.r.phase2a[2][2];
        h=(double)(h/max_g1a)*154;        
        y=156+(154-(int)h); 
        grph1a_act3.setBounds(152, y, 26, ((int)h) );
        
        
        //Graph b
        int max_g1b=ref.r.phase2a[0][3];        
        
        for(int i=0;i<3;i++)
        { 
                if(ref.r.phase2a[i][3]>max_g1b)
                { 
                   max_g1b=ref.r.phase2a[i][3];
                }                        
        }
        System.out.println("Max value for graph 1 b: "+max_g1b);
        
        grph1b_v5.setText(String.valueOf(max_g1b));
        tmp=(int)(max_g1b*0.8);
        grph1b_v4.setText(String.valueOf(tmp));
        tmp=(int)(max_g1b*0.6);
        grph1b_v3.setText(String.valueOf(tmp));
        tmp=(int)(max_g1b*0.4);
        grph1b_v2.setText(String.valueOf(tmp));
        tmp=(int)(max_g1b*0.2);
        grph1b_v1.setText(String.valueOf(tmp));
        
        
        grph1b_y1.setText(String.valueOf(ref.r.phase2a[0][0]));
        
        h=ref.r.phase2a[0][3];
        h=(double)(h/max_g1b)*154;
        y=155+(154-(int)h);         
        grph1b_exp1.setBounds(747, y, 26, ((int)h) );        
        
        h=ref.r.phase2a[0][4];
        h=(double)(h/max_g1b)*154;        
        y=155+(154-(int)h); 
        grph1b_act1.setBounds(774, y, 26, ((int)h) );
        
        
        grph1b_y2.setText(String.valueOf(ref.r.phase2a[1][0]));
        
        h=ref.r.phase2a[1][3];
        h=(double)(h/max_g1b)*154;
        y=155+(154-(int)h);         
        grph1b_exp2.setBounds(654, y, 26, ((int)h) );        
        
        h=ref.r.phase2a[1][4];
        h=(double)(h/max_g1b)*154;        
        y=155+(154-(int)h); 
        grph1b_act2.setBounds(681, y, 26, ((int)h) );
        
        
        grph1b_y3.setText(String.valueOf(ref.r.phase2a[2][0]));
        
        h=ref.r.phase2a[2][3];
        h=(double)(h/max_g1b)*154;
        y=155+(154-(int)h);         
        grph1b_exp3.setBounds(561, y, 26, ((int)h) );        
        
        h=ref.r.phase2a[2][4];
        h=(double)(h/max_g1b)*154;        
        y=155+(154-(int)h); 
        grph1b_act3.setBounds(588, y, 26, ((int)h) );
        
        
        //Set Lights and msg
        int tmpAvg;
        boolean showMsg=true;
        
        //setVisibilityOfComp(true);
        
        //graph a    
                   
         
        //set 3 [0]  
        if(ref.r.phase2a[0][1]==0 || ref.r.phase2a[0][2]==0)
        { lt_c3.setVisible(false); }
        else
        {               
        lt_c3.setVisible(true);
        if(ref.diag2a_Clients[0]>=81)
        { lt_c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_green.png"))); }
        else if(ref.diag2a_Clients[0]>=70 && ref.diag2a_Clients[0]<81)
        { lt_c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_yellow.png"))); }
        else
        { lt_c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); }
        
        }
        
        //set 2 [1]  
        if(ref.r.phase2a[1][1]==0 || ref.r.phase2a[1][2]==0)
        { lt_c2.setVisible(false); }
        else
        {               
        lt_c2.setVisible(true);
        if(ref.diag2a_Clients[1]>=81)
        { lt_c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_green.png"))); }
        else if(ref.diag2a_Clients[1]>=70 && ref.diag2a_Clients[1]<81)
        { lt_c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_yellow.png"))); }        
        else
        { lt_c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); }
        }
        
        //set 1 [2]  
        if(ref.r.phase2a[2][1]==0 || ref.r.phase2a[2][2]==0)
        { lt_c1.setVisible(false); }
        else
        {               
        lt_c1.setVisible(true);
        if(ref.diag2a_Clients[2]>=81)
        { lt_c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_green.png"))); }
        else if(ref.diag2a_Clients[2]>=70 && ref.diag2a_Clients[2]<81)
        { lt_c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_yellow.png"))); }
        else if(ref.diag2a_Clients[2]==0)
        { lt_c1.setVisible(false); }
        else
        { lt_c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); }
        
        }
        
        showMsg=true;
        for(int i=0;i<3;i++)
        {
              if(ref.r.phase2a[i][1]==0 || ref.r.phase2a[i][2]==0)
              { showMsg=false; textA_client.setVisible(false); break; }
        }   
        
        if(showMsg==true)
        {
            textA_client.setVisible(true);
        tmpAvg=((int)(ref.diag2a_Clients[0]+ref.diag2a_Clients[1]+ref.diag2a_Clients[2]))/3;
        //System.out.println(tmpAvg);
        if(tmpAvg>=81)
        {  textA_client.setText("Your company is doing most of the Sales Process related tasks \ncorrectly. To know where the improvements can be made to further \nenhance the output, please proceed to take analytic test."); }
        else if(tmpAvg>=70 && tmpAvg<81)        
        {  textA_client.setText("Your company is doing some of the Sales Process related tasks \ncorrectly. However there seems to be an imperative need to identify \nweak areas to achieve considerable improvement and conversions. \nPlease proceed to take analytic test."); }        
        else
        {  textA_client.setText("Your company is facing alot of challenges in Sales Process Management.\nWe highly recommend you to take analytic test to identify weak areas\nand take immediate corrective actions for considerable improvement \nand conversions."); }
        }
                
        //graph b  
        //set 3 [0]  
        if(ref.r.phase2a[0][3]==0 || ref.r.phase2a[0][4]==0)
        { lt_s3.setVisible(false); }
        else
        {               
        lt_s3.setVisible(true);
        if(ref.diag2a_Sales[0]>=81)
        { lt_s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_green.png"))); }
        else if(ref.diag2a_Sales[0]>=70 && ref.diag2a_Sales[0]<81)
        { lt_s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_yellow.png"))); }        
        else
        { lt_s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); }
        }
        
        
        //set 2 [1]  
        if(ref.r.phase2a[1][3]==0 || ref.r.phase2a[1][4]==0)
        { lt_s2.setVisible(false); }
        else
        {               
        lt_s2.setVisible(true);
        if(ref.diag2a_Sales[1]>=81)
        { lt_s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_green.png"))); }
        else if(ref.diag2a_Sales[1]>=70 && ref.diag2a_Sales[1]<81)
        { lt_s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_yellow.png"))); }        
        else
        { lt_s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); }        
        }
        
        
        //set 1 [2]  
        if(ref.r.phase2a[2][3]==0 || ref.r.phase2a[2][4]==0)
        { lt_s1.setVisible(false); }
        else
        {               
        lt_s1.setVisible(true);
        if(ref.diag2a_Sales[2]>=81)
        { lt_s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_green.png"))); }
        else if(ref.diag2a_Sales[2]>=70 && ref.diag2a_Sales[2]<81)
        { lt_s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_yellow.png"))); }
        else if(ref.diag2a_Sales[2]==0)
        { lt_s1.setVisible(false); }
        else
        { lt_s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/light_red.png"))); }        
        }
        
        
        showMsg=true;
        for(int i=0;i<3;i++)
        {
              if(ref.r.phase2a[i][3]==0 || ref.r.phase2a[i][4]==0)
              { showMsg=false; textA_sales.setVisible(false); break; }
        }   
        
        if(showMsg==true)
        {
            textA_sales.setVisible(true);
        tmpAvg=((int)(ref.diag2a_Sales[0]+ref.diag2a_Sales[1]+ref.diag2a_Sales[2]))/3;        
        if(tmpAvg>=81)
        {  textA_sales.setText("Your company is doing most of the Sales Process related tasks \ncorrectly. To know where the improvements can be made to further \nenhance the output, please proceed to take analytic test."); }
        else if(tmpAvg>=70 && tmpAvg<81)        
        {  textA_sales.setText("Your company is doing some of the Sales Process related tasks \ncorrectly. However there seems to be an imperative need to identify \nweak areas to achieve considerable improvement and conversions. \nPlease proceed to take analytic test."); }
        else
        {  textA_sales.setText("Your company is facing alot of challenges in Sales Process Management.\nWe highly recommend you to take analytic test to identify weak areas\nand take immediate corrective actions for considerable improvement \nand conversions."); }
        }
            
    }
    
    void setVisibilityOfComp(boolean v)
    {
        lt_c1.setVisible(v);
        lt_c2.setVisible(v);
        lt_c3.setVisible(v);
        lt_s1.setVisible(v);
        lt_s2.setVisible(v);
        lt_s3.setVisible(v);
        textA_client.setVisible(v);
        textA_sales.setVisible(v);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel graph1a_bg;
    private javax.swing.JLabel graph1b_bg;
    private javax.swing.JLabel grph1a_act1;
    private javax.swing.JLabel grph1a_act2;
    private javax.swing.JLabel grph1a_act3;
    private javax.swing.JLabel grph1a_exp1;
    private javax.swing.JLabel grph1a_exp2;
    private javax.swing.JLabel grph1a_exp3;
    private javax.swing.JLabel grph1a_v1;
    private javax.swing.JLabel grph1a_v2;
    private javax.swing.JLabel grph1a_v3;
    private javax.swing.JLabel grph1a_v4;
    private javax.swing.JLabel grph1a_v5;
    private javax.swing.JLabel grph1a_y1;
    private javax.swing.JLabel grph1a_y2;
    private javax.swing.JLabel grph1a_y3;
    private javax.swing.JLabel grph1b_act1;
    private javax.swing.JLabel grph1b_act2;
    private javax.swing.JLabel grph1b_act3;
    private javax.swing.JLabel grph1b_exp1;
    private javax.swing.JLabel grph1b_exp2;
    private javax.swing.JLabel grph1b_exp3;
    private javax.swing.JLabel grph1b_v1;
    private javax.swing.JLabel grph1b_v2;
    private javax.swing.JLabel grph1b_v3;
    private javax.swing.JLabel grph1b_v4;
    private javax.swing.JLabel grph1b_v5;
    private javax.swing.JLabel grph1b_y1;
    private javax.swing.JLabel grph1b_y2;
    private javax.swing.JLabel grph1b_y3;
    private javax.swing.JLabel lt_c1;
    private javax.swing.JLabel lt_c2;
    private javax.swing.JLabel lt_c3;
    private javax.swing.JLabel lt_s1;
    private javax.swing.JLabel lt_s2;
    private javax.swing.JLabel lt_s3;
    private javax.swing.JTextArea textA_client;
    private javax.swing.JTextArea textA_sales;
    // End of variables declaration//GEN-END:variables
}
