/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

/**
 *
 * @author Acer
 */
public class PanelPhase3a extends javax.swing.JPanel {

    /**
     * Creates new form PanelPhase3
     */
    private int p3_r1=0;
    
    public PanelPhase3a() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGp_p3_q1 = new javax.swing.ButtonGroup();
        label_p3_q1 = new javax.swing.JLabel();
        radio_p3_q1_1 = new javax.swing.JRadioButton();
        radio_p3_q1_2 = new javax.swing.JRadioButton();
        radio_p3_q1_3 = new javax.swing.JRadioButton();
        radio_p3_q1_4 = new javax.swing.JRadioButton();
        radio_p3_q1_5 = new javax.swing.JRadioButton();
        radio_p3_q1_6 = new javax.swing.JRadioButton();
        Heading = new javax.swing.JLabel();
        diagram = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 540));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        label_p3_q1.setFont(new java.awt.Font("Tahoma", 1, 12));
        label_p3_q1.setText("Q1) Do you have a system/process/mechanism to supply fresh qualified accounts for your sales process? ");
        add(label_p3_q1);
        label_p3_q1.setBounds(50, 260, 650, 19);

        btnGp_p3_q1.add(radio_p3_q1_1);
        radio_p3_q1_1.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p3_q1_1.setText("Yes, we have a database mining team / executives who search for new qualified accounts on a dedicated basis.");
        radio_p3_q1_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p3_q1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p3_q1_1.setOpaque(false);
        radio_p3_q1_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p3_q1_1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p3_q1_1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p3_q1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p3_q1_1ActionPerformed(evt);
            }
        });
        add(radio_p3_q1_1);
        radio_p3_q1_1.setBounds(125, 305, 650, 27);

        btnGp_p3_q1.add(radio_p3_q1_2);
        radio_p3_q1_2.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p3_q1_2.setText("Yes, we have a database mining team/ executives who search for new qualified accounts on a shared basis. ");
        radio_p3_q1_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p3_q1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p3_q1_2.setOpaque(false);
        radio_p3_q1_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p3_q1_2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p3_q1_2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p3_q1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p3_q1_2ActionPerformed(evt);
            }
        });
        add(radio_p3_q1_2);
        radio_p3_q1_2.setBounds(125, 330, 650, 27);

        btnGp_p3_q1.add(radio_p3_q1_3);
        radio_p3_q1_3.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p3_q1_3.setText("No, we take help of external agencies from time to time and are satisfied with their performance. ");
        radio_p3_q1_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p3_q1_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p3_q1_3.setOpaque(false);
        radio_p3_q1_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p3_q1_3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p3_q1_3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p3_q1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p3_q1_3ActionPerformed(evt);
            }
        });
        add(radio_p3_q1_3);
        radio_p3_q1_3.setBounds(125, 355, 650, 27);

        btnGp_p3_q1.add(radio_p3_q1_4);
        radio_p3_q1_4.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p3_q1_4.setText("No, we take help of external agencies from time to time and are not satisfied with their performance.");
        radio_p3_q1_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p3_q1_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p3_q1_4.setOpaque(false);
        radio_p3_q1_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p3_q1_4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p3_q1_4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p3_q1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p3_q1_4ActionPerformed(evt);
            }
        });
        add(radio_p3_q1_4);
        radio_p3_q1_4.setBounds(125, 380, 650, 27);

        btnGp_p3_q1.add(radio_p3_q1_5);
        radio_p3_q1_5.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p3_q1_5.setText("No, we do not have any in house or outsourced mechanism and our sales team is expected to do the same. ");
        radio_p3_q1_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p3_q1_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p3_q1_5.setOpaque(false);
        radio_p3_q1_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p3_q1_5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p3_q1_5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p3_q1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p3_q1_5ActionPerformed(evt);
            }
        });
        add(radio_p3_q1_5);
        radio_p3_q1_5.setBounds(125, 405, 650, 27);

        btnGp_p3_q1.add(radio_p3_q1_6);
        radio_p3_q1_6.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p3_q1_6.setText("No, we are dependent on leads supplied by our partners. ");
        radio_p3_q1_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p3_q1_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p3_q1_6.setOpaque(false);
        radio_p3_q1_6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p3_q1_6.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p3_q1_6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p3_q1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p3_q1_6ActionPerformed(evt);
            }
        });
        add(radio_p3_q1_6);
        radio_p3_q1_6.setBounds(125, 430, 650, 27);

        Heading.setFont(new java.awt.Font("Tahoma", 1, 16));
        Heading.setForeground(new java.awt.Color(12, 120, 73));
        Heading.setText("3. Generate Qualified Prospect List:");
        add(Heading);
        Heading.setBounds(20, 220, 360, 20);

        diagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/SPDiag_3_1.gif"))); // NOI18N
        add(diagram);
        diagram.setBounds(155, 20, 590, 170);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void radio_p3_q1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p3_q1_1ActionPerformed
        // TODO add your handling code here:
        p3_r1=1;
    }//GEN-LAST:event_radio_p3_q1_1ActionPerformed

    private void radio_p3_q1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p3_q1_5ActionPerformed
        // TODO add your handling code here:
        p3_r1=5;
    }//GEN-LAST:event_radio_p3_q1_5ActionPerformed

    private void radio_p3_q1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p3_q1_2ActionPerformed
        // TODO add your handling code here:
        p3_r1=2;
    }//GEN-LAST:event_radio_p3_q1_2ActionPerformed

    private void radio_p3_q1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p3_q1_3ActionPerformed
        // TODO add your handling code here:
        p3_r1=3;
    }//GEN-LAST:event_radio_p3_q1_3ActionPerformed

    private void radio_p3_q1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p3_q1_4ActionPerformed
        // TODO add your handling code here:
        p3_r1=4;
    }//GEN-LAST:event_radio_p3_q1_4ActionPerformed

    private void radio_p3_q1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p3_q1_6ActionPerformed
        // TODO add your handling code here:
        p3_r1=6;
    }//GEN-LAST:event_radio_p3_q1_6ActionPerformed

    //----------------------- MyMethods-----------------------
    public boolean assignAllData(Record ref)
    {
        String errMsg="Please select an option!";                      
                
        try
        {
            if(p3_r1==0)                     
                { throw new Exception(errMsg); }
            else
                { ref.phase3[0]=p3_r1;  }                                      
        }catch(Exception e)
        {
            //System.out.println(e.getMessage());
            SPA.panelController(e.getMessage(), new int[]{2,0,1,3,1,0});            
            return(false);
        }
        
        SPA.panelController(null, new int[]{0,0,0,3,1,0});
        return(true);
    }
    
    void resetPanel()
    {
        p3_r1=0;
        btnGp_p3_q1.clearSelection();      
    }
    
    void loadPanel(Record r)
    {           
        p3_r1=r.phase3[0];        
        
        switch(r.phase3[0]) 
        {
            case 1 : radio_p3_q1_1.setSelected(true); break;
            case 2 : radio_p3_q1_2.setSelected(true); break;
            case 3 : radio_p3_q1_3.setSelected(true); break;
            case 4 : radio_p3_q1_4.setSelected(true); break;
            case 5 : radio_p3_q1_5.setSelected(true); break;
            case 6 : radio_p3_q1_6.setSelected(true); break;
        }       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup btnGp_p3_q1;
    private javax.swing.JLabel diagram;
    private javax.swing.JLabel label_p3_q1;
    private javax.swing.JRadioButton radio_p3_q1_1;
    private javax.swing.JRadioButton radio_p3_q1_2;
    private javax.swing.JRadioButton radio_p3_q1_3;
    private javax.swing.JRadioButton radio_p3_q1_4;
    private javax.swing.JRadioButton radio_p3_q1_5;
    private javax.swing.JRadioButton radio_p3_q1_6;
    // End of variables declaration//GEN-END:variables
}
