/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

/**
 *
 * @author Gagandeep
 */
public class PanelBubble extends javax.swing.JPanel {

    /**
     * Creates new form PanelBubble
     */
    
    String msg="";
    int code[]=new int[6];
    
    public PanelBubble() {
        initComponents();
        //getcode("Please complete all Entries!", 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        symbol = new javax.swing.JLabel();
        msg_Line1 = new javax.swing.JLabel();
        msg_Line2 = new javax.swing.JLabel();
        btn_moreInfo = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(238, 88));
        setLayout(null);

        symbol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/Alert.png"))); // NOI18N
        symbol.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(symbol);
        symbol.setBounds(9, 14, 30, 40);

        msg_Line1.setText("Error displaying message!");
        add(msg_Line1);
        msg_Line1.setBounds(45, 13, 165, 14);
        add(msg_Line2);
        msg_Line2.setBounds(45, 30, 150, 14);

        btn_moreInfo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_moreInfo.setForeground(new java.awt.Color(0, 102, 0));
        btn_moreInfo.setText("Click here for More Information !");
        btn_moreInfo.setBorderPainted(false);
        btn_moreInfo.setContentAreaFilled(false);
        btn_moreInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_moreInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moreInfoActionPerformed(evt);
            }
        });
        add(btn_moreInfo);
        btn_moreInfo.setBounds(14, 47, 210, 21);

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/bbl_close_1.png"))); // NOI18N
        btn_close.setBorderPainted(false);
        btn_close.setContentAreaFilled(false);
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setFocusPainted(false);
        btn_close.setPreferredSize(new java.awt.Dimension(14, 14));
        btn_close.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/bbl_close_3.png"))); // NOI18N
        btn_close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/bbl_close_2.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        add(btn_close);
        btn_close.setBounds(203, 8, 20, 18);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/Bubble.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 237, 87);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_moreInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moreInfoActionPerformed
        // TODO add your handling code here:
        Dialog_ErrorHandler d= new Dialog_ErrorHandler(null, true);
        d.recieveInfo(msg, code);
        d.setVisible(true);
        
    }//GEN-LAST:event_btn_moreInfoActionPerformed

    private void setSymbol()
    {
        if(code[0]==2)
        {  symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/Alert.png"))); }
        else    
        {  symbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/Error.png"))); }
    }
    
    public void getState(String m, int s[])
    {   
        msg=m;
        code=s; 
     
        setVisible(true);
        setSymbol();
        
        String tmp="",tmp2="";                
        for(int i=0;i<msg.length();i++)
        {
            if(i<30)
            { tmp+=msg.charAt(i);  }            
            else if(i==30 && (msg.charAt(i+1)!=' ') )
            { 
              tmp+='-';  
              tmp2+=msg.charAt(i);
            }
            else
            { tmp2+=msg.charAt(i); }            
        }
        //System.out.println(tmp);
        msg_Line1.setText(tmp);
        msg_Line2.setText(tmp2);
        
        
        
        if(s[0]==1)
        { 
           Dialog_ErrorHandler d= new Dialog_ErrorHandler(null, true);
           d.recieveInfo(msg, code);
           d.setVisible(true);
        }
        
    }
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_moreInfo;
    private javax.swing.JLabel msg_Line1;
    private javax.swing.JLabel msg_Line2;
    private javax.swing.JLabel symbol;
    // End of variables declaration//GEN-END:variables
}
