/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

import java.awt.Color;

/**
 *
 * @author Gagandeep
 */
public class Panel_GettingStarted extends javax.swing.JPanel {

    /**
     * Creates new form Panel_GettingStarted
     */
    
    DatabaseHandler db_ref=new DatabaseHandler();
    Configuration cnf_ref=new Configuration();  
 
    
    public Panel_GettingStarted() {
        initComponents();      
        lb_missmatch.setVisible(false);
        lb_invalidKey.setVisible(false);
        btn_format.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textF_fNm = new javax.swing.JTextField();
        textF_lNm = new javax.swing.JTextField();
        lbl_mail = new javax.swing.JLabel();
        textF_eMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textF_country = new javax.swing.JTextField();
        lbl_cmp = new javax.swing.JLabel();
        textF_cmp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textF_add = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textF_city = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textF_state = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textF_zip = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textF_dsn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textF_wb = new javax.swing.JTextField();
        btn_format = new javax.swing.JButton();
        btn_getWrkBk = new javax.swing.JButton();
        textF_key1 = new javax.swing.JTextField();
        textF_key2 = new javax.swing.JTextField();
        textF_key3 = new javax.swing.JTextField();
        textF_key4 = new javax.swing.JTextField();
        chBx_1 = new javax.swing.JCheckBox();
        chBx_2 = new javax.swing.JCheckBox();
        btn_submit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        passF_pass = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        paasF_cnf = new javax.swing.JPasswordField();
        btn_chk_key = new javax.swing.JButton();
        lb_missmatch = new javax.swing.JLabel();
        lbl_ph = new javax.swing.JLabel();
        textF_phno = new javax.swing.JTextField();
        lb_invalidKey = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        jLabel1.setText("First Name :");
        add(jLabel1);
        jLabel1.setBounds(60, 112, 58, 14);

        jLabel2.setText("Last Name :");
        add(jLabel2);
        jLabel2.setBounds(60, 145, 57, 14);

        textF_fNm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_fNm.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textF_fNm.setNextFocusableComponent(textF_lNm);
        add(textF_fNm);
        textF_fNm.setBounds(160, 110, 169, 20);

        textF_lNm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_lNm.setNextFocusableComponent(textF_cmp);
        add(textF_lNm);
        textF_lNm.setBounds(160, 143, 170, 20);

        lbl_mail.setText("E-Mail :");
        add(lbl_mail);
        lbl_mail.setBounds(60, 214, 35, 14);

        textF_eMail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_eMail.setNextFocusableComponent(textF_phno);
        add(textF_eMail);
        textF_eMail.setBounds(160, 212, 170, 20);

        jLabel5.setText("Country :");
        add(jLabel5);
        jLabel5.setBounds(60, 379, 46, 14);

        textF_country.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_country.setNextFocusableComponent(textF_zip);
        add(textF_country);
        textF_country.setBounds(160, 377, 170, 20);

        lbl_cmp.setText("Company :");
        add(lbl_cmp);
        lbl_cmp.setBounds(60, 178, 52, 14);

        textF_cmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_cmp.setNextFocusableComponent(textF_eMail);
        add(textF_cmp);
        textF_cmp.setBounds(160, 176, 170, 20);

        jLabel7.setText("Address :");
        add(jLabel7);
        jLabel7.setBounds(60, 280, 46, 14);

        textF_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_add.setNextFocusableComponent(textF_city);
        add(textF_add);
        textF_add.setBounds(160, 278, 170, 20);

        jLabel8.setText("City :");
        add(jLabel8);
        jLabel8.setBounds(60, 313, 26, 14);

        textF_city.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_city.setNextFocusableComponent(textF_state);
        add(textF_city);
        textF_city.setBounds(160, 311, 170, 20);

        jLabel9.setText("State :");
        add(jLabel9);
        jLabel9.setBounds(60, 346, 33, 14);

        textF_state.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_state.setNextFocusableComponent(textF_country);
        add(textF_state);
        textF_state.setBounds(160, 344, 170, 20);

        jLabel10.setText("Zip/Postal Code :");
        add(jLabel10);
        jLabel10.setBounds(60, 412, 82, 14);

        textF_zip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_zip.setNextFocusableComponent(textF_dsn);
        add(textF_zip);
        textF_zip.setBounds(160, 410, 170, 20);

        jLabel11.setText("Data Source Name :");
        add(jLabel11);
        jLabel11.setBounds(450, 100, 96, 14);

        textF_dsn.setToolTipText("Data Source Name used in ODBC connection");
        textF_dsn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_dsn.setNextFocusableComponent(btn_getWrkBk);
        textF_dsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textF_dsnActionPerformed(evt);
            }
        });
        add(textF_dsn);
        textF_dsn.setBounds(560, 98, 190, 20);

        jLabel12.setText("WorkBook Path :");
        add(jLabel12);
        jLabel12.setBounds(450, 130, 90, 14);

        textF_wb.setEditable(false);
        textF_wb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        add(textF_wb);
        textF_wb.setBounds(560, 128, 190, 20);

        btn_format.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/format_1.png"))); // NOI18N
        btn_format.setBorderPainted(false);
        btn_format.setContentAreaFilled(false);
        btn_format.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_format.setDisabledIcon(null);
        btn_format.setFocusPainted(false);
        btn_format.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/format_3.png"))); // NOI18N
        btn_format.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/format_2.png"))); // NOI18N
        btn_format.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formatActionPerformed(evt);
            }
        });
        add(btn_format);
        btn_format.setBounds(560, 155, 90, 23);

        btn_getWrkBk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/process_1.png"))); // NOI18N
        btn_getWrkBk.setBorderPainted(false);
        btn_getWrkBk.setContentAreaFilled(false);
        btn_getWrkBk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_getWrkBk.setFocusPainted(false);
        btn_getWrkBk.setNextFocusableComponent(passF_pass);
        btn_getWrkBk.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/process_3.png"))); // NOI18N
        btn_getWrkBk.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/process_2.png"))); // NOI18N
        btn_getWrkBk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getWrkBkActionPerformed(evt);
            }
        });
        add(btn_getWrkBk);
        btn_getWrkBk.setBounds(660, 155, 90, 23);

        textF_key1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_key1.setNextFocusableComponent(textF_key2);
        add(textF_key1);
        textF_key1.setBounds(470, 372, 50, 20);

        textF_key2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_key2.setNextFocusableComponent(textF_key3);
        add(textF_key2);
        textF_key2.setBounds(540, 372, 50, 20);

        textF_key3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_key3.setNextFocusableComponent(textF_key4);
        add(textF_key3);
        textF_key3.setBounds(610, 372, 50, 20);

        textF_key4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_key4.setNextFocusableComponent(btn_chk_key);
        add(textF_key4);
        textF_key4.setBounds(680, 372, 50, 20);

        chBx_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chBx_1.setText("I am a genuine buyer of this product.");
        chBx_1.setNextFocusableComponent(chBx_2);
        chBx_1.setOpaque(false);
        add(chBx_1);
        chBx_1.setBounds(150, 465, 500, 20);

        chBx_2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chBx_2.setText("I accept the terms and conditions in the License Agreement. ");
        chBx_2.setOpaque(false);
        add(chBx_2);
        chBx_2.setBounds(150, 490, 500, 20);

        btn_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Resgistration/submit_1.png"))); // NOI18N
        btn_submit.setBorderPainted(false);
        btn_submit.setContentAreaFilled(false);
        btn_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_submit.setFocusPainted(false);
        btn_submit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Resgistration/submit_3.png"))); // NOI18N
        btn_submit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Resgistration/submit_2.png"))); // NOI18N
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        add(btn_submit);
        btn_submit.setBounds(290, 530, 90, 31);

        jLabel14.setText("Administrator Password :");
        add(jLabel14);
        jLabel14.setBounds(465, 234, 120, 14);

        passF_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        passF_pass.setNextFocusableComponent(paasF_cnf);
        add(passF_pass);
        passF_pass.setBounds(600, 232, 136, 20);

        jLabel15.setText("Confirm Password :");
        add(jLabel15);
        jLabel15.setBounds(465, 266, 93, 14);

        paasF_cnf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        paasF_cnf.setNextFocusableComponent(textF_key1);
        paasF_cnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paasF_cnfActionPerformed(evt);
            }
        });
        add(paasF_cnf);
        paasF_cnf.setBounds(600, 264, 136, 20);

        btn_chk_key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/check_1.png"))); // NOI18N
        btn_chk_key.setBorderPainted(false);
        btn_chk_key.setContentAreaFilled(false);
        btn_chk_key.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_chk_key.setFocusPainted(false);
        btn_chk_key.setNextFocusableComponent(chBx_1);
        btn_chk_key.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/check_3.png"))); // NOI18N
        btn_chk_key.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/check_2.png"))); // NOI18N
        btn_chk_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chk_keyActionPerformed(evt);
            }
        });
        add(btn_chk_key);
        btn_chk_key.setBounds(640, 410, 90, 23);

        lb_missmatch.setForeground(new java.awt.Color(255, 51, 51));
        lb_missmatch.setText("Password Mismatch!");
        add(lb_missmatch);
        lb_missmatch.setBounds(600, 294, 97, 14);

        lbl_ph.setText("Phone No :");
        add(lbl_ph);
        lbl_ph.setBounds(60, 247, 70, 14);

        textF_phno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 135, 144)));
        textF_phno.setNextFocusableComponent(textF_add);
        add(textF_phno);
        textF_phno.setBounds(160, 245, 170, 20);

        lb_invalidKey.setForeground(new java.awt.Color(255, 0, 0));
        lb_invalidKey.setText("Invalid Serial Key!");
        add(lb_invalidKey);
        lb_invalidKey.setBounds(530, 415, 100, 14);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Resgistration/Registration_BG.gif"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        analyseAllData();
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_getWrkBkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getWrkBkActionPerformed
        // TODO add your handling code here:     
        chkDSN();
    }//GEN-LAST:event_btn_getWrkBkActionPerformed
  
    private void paasF_cnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paasF_cnfActionPerformed
        // TODO add your handling code here:        
        chkPass();
    }//GEN-LAST:event_paasF_cnfActionPerformed

    private void textF_dsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textF_dsnActionPerformed
        // TODO add your handling code here:
        chkDSN();
    }//GEN-LAST:event_textF_dsnActionPerformed

    private void btn_chk_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chk_keyActionPerformed
        // TODO add your handling code here:
        if(chkKey()==false)
        { lb_invalidKey.setVisible(true); }
        else
        { lb_invalidKey.setVisible(false); }
    }//GEN-LAST:event_btn_chk_keyActionPerformed

    private void btn_formatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formatActionPerformed
        // TODO add your handling code here:
        DatabaseHandler tmpDb = new DatabaseHandler();
        tmpDb.dataSourceName = textF_dsn.getText();
        tmpDb.createTable();
        textF_wb.setText("Formatting Done !"); 
        textF_wb.setCaretPosition(0);
        btn_format.setVisible(false);
        //chkDSN();
    }//GEN-LAST:event_btn_formatActionPerformed

    void getReferences(DatabaseHandler db, Configuration c)
    {
        db_ref=db;
        cnf_ref=c;
    }
   
   
    
    private boolean chkDSN()
    {
        DatabaseHandler tmpDb=new DatabaseHandler();
        tmpDb.dataSourceName=textF_dsn.getText();
        
        int db_chk=tmpDb.checkConnection();
        
        if(db_chk==0)
        {
            btn_format.setVisible(false);
            textF_wb.setText("Data Source Name Not Found");
            return(false);
        }
        else if(db_chk==-1)
        {
            if(!tmpDb.workBook.equals("") && !tmpDb.checkReadOnly(false))
            {
                textF_wb.setText("Format Workbook : "+tmpDb.workBook);  
                textF_wb.setCaretPosition(0);
                btn_format.setVisible(true);                
        
            }
            else
            {
                btn_format.setVisible(false);
                textF_wb.setText("Incompatible or Missing Workbook!");
            }
            return(false);
        }
        else
        {
            btn_format.setVisible(false);
            textF_wb.setText(tmpDb.workBook);            
            return(true);
        }
    }
    
    private boolean chkPass()
    {        
        if(passF_pass.getText().equals(paasF_cnf.getText()))
        {
            lb_missmatch.setVisible(false);            
            return(true);
        }
        else
        {
            lb_missmatch.setVisible(true);
            return(false);
        }       
        
    }
    
    private boolean chkKey() 
    {
        /*
        int t;
        
        try
        {
            t=Integer.parseInt(textF_key1.getText());            
            if(t<1000 || t>9999)
            {   return(false); }
                        
            t=Integer.parseInt(textF_key2.getText());
            if(t<1000 || t>9999)
            {   return(false); }
            
            t=Integer.parseInt(textF_key3.getText());
            if(t<1000 || t>9999)
            {   return(false); }
            
            t=Integer.parseInt(textF_key4.getText());
            if(t<1000 || t>9999)
            {   return(false); }        
        }catch(NumberFormatException e)
        { return(false); }
        
        */
        
        int k1=0,k2=0,k3=0,k4=0;
        
        try
        {
            k1=Integer.parseInt(textF_key1.getText());                        
                        
            k2=Integer.parseInt(textF_key2.getText());
                        
            k3=Integer.parseInt(textF_key3.getText());            
            
            k4=Integer.parseInt(textF_key4.getText());
            
        }catch(NumberFormatException e)
        { 
            textF_fNm.setEditable(true);
            textF_lNm.setEditable(true);
            textF_cmp.setEditable(true);
            textF_eMail.setEditable(true);            
            textF_phno.setEditable(true);
            textF_city.setEditable(true);
            textF_state.setEditable(true);   
            textF_country.setEditable(true);
            return(false); 
        }
        
        if(k1==9553 && k2==8011 && k3==7591 && k4==9717)
        {
            textF_fNm.setText("Harmeet Singh");                                 textF_fNm.setEditable(false);
            textF_lNm.setText("Bahra");                                         textF_lNm.setEditable(false);
            textF_cmp.setText("Sales Process & Marketing Consultant");          textF_cmp.setEditable(false);
            textF_eMail.setText("harmeetakaharry@gmail.com");                   textF_eMail.setEditable(false);            
            textF_phno.setText("9717155311");                                   textF_phno.setEditable(false);
            textF_city.setText("New Delhi");                                    textF_city.setEditable(false);
            textF_state.setText("Delhi");                                       textF_state.setEditable(false);   
            textF_country.setText("India");                                     textF_country.setEditable(false);
        }else if(k1==5112 && k2==1801 && k3==7591 && k4==9350)
        {
            textF_fNm.setText("Hargeet Kaur");                                  textF_fNm.setEditable(false);
            textF_lNm.setText("Bhatia");                                        textF_lNm.setEditable(false);
            textF_cmp.setText("Home");                                          textF_cmp.setEditable(false);
            textF_eMail.setText("raavibhatia@yahoo.in");                        textF_eMail.setEditable(false);            
            textF_phno.setText("9350511201");                                   textF_phno.setEditable(false);
            textF_city.setText("New Delhi");                                    textF_city.setEditable(false);
            textF_state.setText("Delhi");                                       textF_state.setEditable(false);   
            textF_country.setText("India");                                     textF_country.setEditable(false);
        }else if(k1==4949 && k2==3091 && k3==7591 && k4==9910)
        {
            textF_fNm.setText("Amanpreet Singh");                               textF_fNm.setEditable(false);
            textF_lNm.setText("Chauhan");                                       textF_lNm.setEditable(false);
            textF_cmp.setText("Home");                                          textF_cmp.setEditable(false);
            textF_eMail.setText("armaan.chauhans@gmail.com");                   textF_eMail.setEditable(false);            
            textF_phno.setText("9910494991");                                   textF_phno.setEditable(false);
            textF_city.setText("New Delhi");                                    textF_city.setEditable(false);
            textF_state.setText("Delhi");                                       textF_state.setEditable(false);   
            textF_country.setText("India");                                     textF_country.setEditable(false);
        }else if( (k1==4546 && k2==4011 && k3==7591 && k4==2913) && Diagnostic.trial==true)
        {            
            textF_lNm.setText("(Trial Version)");                  textF_lNm.setEditable(false); 
            
            textF_fNm.setEditable(true);            
            textF_cmp.setEditable(true);
            textF_eMail.setEditable(true);            
            textF_phno.setEditable(true);
            textF_city.setEditable(true);
            textF_state.setEditable(true);   
            textF_country.setEditable(true);
            
            Dialog_reg_child d=new Dialog_reg_child(null, true);
            d.getMessage("This Serial key belongs to Trial\nVersion! The application will\nexpire in 1 day!", 0);
            d.setVisible(true);
            
        }else if(k1==6511 && k2==5201 && k3==7591 && k4==9113)
        {            
            textF_fNm.setEditable(true);
            textF_lNm.setEditable(true);
            textF_cmp.setEditable(true);
            textF_eMail.setEditable(true);            
            textF_phno.setEditable(true);
            textF_city.setEditable(true);
            textF_state.setEditable(true);   
            textF_country.setEditable(true);
        }
        else
        {
            textF_fNm.setEditable(true);
            textF_lNm.setEditable(true);
            textF_cmp.setEditable(true);
            textF_eMail.setEditable(true);            
            textF_phno.setEditable(true);
            textF_city.setEditable(true);
            textF_state.setEditable(true);   
            textF_country.setEditable(true);
            return(false);
        }
        
                
        return(true);
    }
         
    private boolean chkAgreement()
    {
        boolean flag=true;
        if(chBx_1.isSelected()==false)
        {  chBx_1.setForeground(Color.red); flag=false; }
        else
        {  chBx_1.setForeground(Color.black); }
        
        if(chBx_2.isSelected()==false)
        {  chBx_2.setForeground(Color.red); flag=false; }
        else
        {  chBx_2.setForeground(Color.black); }       
        
        return(flag);
    }
    
    boolean analyseAllData()
    {
        String errMsg="Please complete all Entries!";        
        String str="";              
        
        try
        {
            
            str=textF_fNm.getText();
            if(str.equals(""))
            {  throw new Exception(errMsg);  }           
            cnf_ref.firstName=str;
            
            str=textF_lNm.getText();
            if(str.equals(""))
            { throw new Exception(errMsg);  }            
            cnf_ref.lastName=str;
            
            str=textF_cmp.getText();
            if(str.equals(""))
            {  throw new Exception(errMsg);  }            
            cnf_ref.company=str;
            
            str=textF_eMail.getText();
            if(str.equals(""))
            { throw new Exception(errMsg);  }            
            cnf_ref.email=str;
            
            str=textF_country.getText();
            if(str.equals(""))
            {  throw new Exception(errMsg);  }
            cnf_ref.country=str;          

            
            str=textF_add.getText();
            if(str.equals(""))
            {  throw new Exception(errMsg);  }
            cnf_ref.add=str;
            
            str=textF_city.getText();
            if(str.equals(""))
            {  throw new Exception(errMsg);  }
            cnf_ref.city=str;
            
            str=textF_state.getText();
            if(str.equals(""))
            {  throw new Exception(errMsg);  }
            cnf_ref.state=str;
            
            
            str=textF_zip.getText();
            int itmp;
            if(!str.equals(""))
            {   
                itmp=Integer.parseInt(str);
                if(itmp<100000 || itmp>999999)
                {  throw new NumberFormatException("Invalid Zip Code!"); }
            }
            else
            {  throw new NumberFormatException("Invalid Zip Code!"); }               
            cnf_ref.zipCode=itmp;
            
            long tmp=Long.parseLong(textF_phno.getText());            
            long max=Long.parseLong("9999999999");
            if(tmp>=max)
            {  lbl_ph.setForeground(Color.red);  throw new NumberFormatException("Invalid Phone No!"); }
            lbl_ph.setForeground(Color.black); 
            cnf_ref.phno=tmp;   
            
            if(chkPass()==false)
            {  throw new Exception(errMsg);  }
            cnf_ref.loginPass=passF_pass.getText();
            
            if(chkDSN()==false)
            {  throw new Exception(errMsg);  }
            cnf_ref.dataSourceName=db_ref.dataSourceName=textF_dsn.getText();
            cnf_ref.databaseFilePath=db_ref.workBook=textF_wb.getText();
            
            if(chkKey()==false)
            {                 
               lb_invalidKey.setVisible(true);
               throw new Exception(errMsg);
            }  
            else
            {                 
                lb_invalidKey.setVisible(false); 
                cnf_ref.activationCode[0]=Integer.parseInt(textF_key1.getText());
                cnf_ref.activationCode[1]=Integer.parseInt(textF_key2.getText());
                cnf_ref.activationCode[2]=Integer.parseInt(textF_key3.getText());
                cnf_ref.activationCode[3]=Integer.parseInt(textF_key4.getText());                
            }
            
            cnf_ref.lastBackupDate="";
            cnf_ref.errorState=0;
            cnf_ref.prgCounter=1;
            cnf_ref.currMaxRID=0;
            cnf_ref.logStatus=1;          
            cnf_ref.badUser=false;    
            
            cnf_ref.setDate();
            
            if(chkAgreement())
            { cnf_ref.writeConfigFile(); //System.out.println("Registered!");   //WRITE FILE
              new LogHandler().writeToLog(31);
              Dialog_reg_child d=new Dialog_reg_child(null, true);
              d.getMessage("Congratulations "+cnf_ref.firstName+",\nYou have registered succcessfully.\nPlease click exit and restart the\napplication!",1);
              d.setVisible(true);
            }   
            else
            {  throw new Exception(errMsg);  }
            
        }catch(NumberFormatException e)
        {
            //System.out.println("Number"+e.getMessage());
            Dialog_reg_child d=new Dialog_reg_child(null, true);
            d.getMessage("Invalid Phone Number or Zip Code!",0);
            d.setVisible(true);
            return(false);
        }catch(Exception e)
        { //System.out.println("Exception :"+e.getMessage()); 
          Dialog_reg_child d=new Dialog_reg_child(null, true);
          d.getMessage(e.getMessage(),0);
          d.setVisible(true);
          return(false);
        }
        
        
        return(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_chk_key;
    private javax.swing.JButton btn_format;
    private javax.swing.JButton btn_getWrkBk;
    private javax.swing.JButton btn_submit;
    private javax.swing.JCheckBox chBx_1;
    private javax.swing.JCheckBox chBx_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_invalidKey;
    private javax.swing.JLabel lb_missmatch;
    private javax.swing.JLabel lbl_cmp;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_ph;
    private javax.swing.JPasswordField paasF_cnf;
    private javax.swing.JPasswordField passF_pass;
    private javax.swing.JTextField textF_add;
    private javax.swing.JTextField textF_city;
    private javax.swing.JTextField textF_cmp;
    private javax.swing.JTextField textF_country;
    private javax.swing.JTextField textF_dsn;
    private javax.swing.JTextField textF_eMail;
    private javax.swing.JTextField textF_fNm;
    private javax.swing.JTextField textF_key1;
    private javax.swing.JTextField textF_key2;
    private javax.swing.JTextField textF_key3;
    private javax.swing.JTextField textF_key4;
    private javax.swing.JTextField textF_lNm;
    private javax.swing.JTextField textF_phno;
    private javax.swing.JTextField textF_state;
    private javax.swing.JTextField textF_wb;
    private javax.swing.JTextField textF_zip;
    // End of variables declaration//GEN-END:variables
}
