/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPhase5b.java
 *
 * Created on Mar 1, 2012, 3:20:48 PM
 */
package salesPackage;

/**
 *
 * @author user
 */
public class PanelPhase5d extends javax.swing.JPanel {

    /** Creates new form PanelPhase5b */
    public PanelPhase5d() {
        initComponents();
    }
    public int p5_r4;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Gp_p5_q4 = new javax.swing.ButtonGroup();
        label_p5_q4 = new javax.swing.JLabel();
        radio_p5_q4_1 = new javax.swing.JRadioButton();
        radio_p5_q4_2 = new javax.swing.JRadioButton();
        radio_p5_q4_3 = new javax.swing.JRadioButton();
        diagram = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 540));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        label_p5_q4.setFont(new java.awt.Font("Tahoma", 1, 12));
        label_p5_q4.setText("Q4) Does your team use any CRM for managing sales projections? If yes, is this the way you review sales with your team? Please elaborate.");
        add(label_p5_q4);
        label_p5_q4.setBounds(20, 280, 870, 30);

        btn_Gp_p5_q4.add(radio_p5_q4_1);
        radio_p5_q4_1.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p5_q4_1.setText("Yes we have a CRM for managing sales projections and use it to the fullest. ");
        radio_p5_q4_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p5_q4_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p5_q4_1.setOpaque(false);
        radio_p5_q4_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p5_q4_1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p5_q4_1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p5_q4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p5_q4_1ActionPerformed(evt);
            }
        });
        add(radio_p5_q4_1);
        radio_p5_q4_1.setBounds(225, 380, 450, 23);

        btn_Gp_p5_q4.add(radio_p5_q4_2);
        radio_p5_q4_2.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p5_q4_2.setText("Yes we have a CRM but do not use it that aggressively. ");
        radio_p5_q4_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p5_q4_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p5_q4_2.setOpaque(false);
        radio_p5_q4_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p5_q4_2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p5_q4_2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p5_q4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p5_q4_2ActionPerformed(evt);
            }
        });
        add(radio_p5_q4_2);
        radio_p5_q4_2.setBounds(225, 405, 450, 27);

        btn_Gp_p5_q4.add(radio_p5_q4_3);
        radio_p5_q4_3.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p5_q4_3.setText("No we do not have a CRM or a Sales Template. ");
        radio_p5_q4_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p5_q4_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p5_q4_3.setOpaque(false);
        radio_p5_q4_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p5_q4_3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p5_q4_3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p5_q4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p5_q4_3ActionPerformed(evt);
            }
        });
        add(radio_p5_q4_3);
        radio_p5_q4_3.setBounds(225, 430, 450, 27);

        diagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/SPDiag_5_4.gif"))); // NOI18N
        add(diagram);
        diagram.setBounds(155, 20, 590, 170);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void radio_p5_q4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p5_q4_1ActionPerformed
        // TODO add your handling code here:
        p5_r4=1;
}//GEN-LAST:event_radio_p5_q4_1ActionPerformed

    private void radio_p5_q4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p5_q4_2ActionPerformed
        // TODO add your handling code here:
        p5_r4=2;
}//GEN-LAST:event_radio_p5_q4_2ActionPerformed

    private void radio_p5_q4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p5_q4_3ActionPerformed
        // TODO add your handling code here:
        p5_r4=3;
}//GEN-LAST:event_radio_p5_q4_3ActionPerformed

    //----------------------- MyMethods-----------------------
    public boolean assignAllData(Record ref)
    {
        String errMsg="Please select an option!";                      
                
        try
        {
            if(p5_r4==0)
                { throw new Exception(errMsg); }
            else
                { 
                  ref.phase5[3]=p5_r4;                    
                }                                      
        }catch(Exception e)
        {
            //System.out.println(e.getMessage());
            SPA.panelController(e.getMessage(), new int[]{2,0,1,3,1,0});
            return(false);
        }
        
        SPA.panelController(null, new int[]{0,0,0,3,1,0});
        return(true);
    }
    
    void resetPanel()
    {
        p5_r4=0;
        btn_Gp_p5_q4.clearSelection();      
    }
    
    void loadPanel(Record r)
    {           
        p5_r4=r.phase5[3];        
        
        switch(r.phase5[3]) 
        {
            case 1 : radio_p5_q4_1.setSelected(true); break;
            case 2 : radio_p5_q4_2.setSelected(true); break;
            case 3 : radio_p5_q4_3.setSelected(true); break;            
        }       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup btn_Gp_p5_q4;
    private javax.swing.JLabel diagram;
    private javax.swing.JLabel label_p5_q4;
    private javax.swing.JRadioButton radio_p5_q4_1;
    private javax.swing.JRadioButton radio_p5_q4_2;
    private javax.swing.JRadioButton radio_p5_q4_3;
    // End of variables declaration//GEN-END:variables
}
