package salesPackage;

public class PanelPhase2_0 extends javax.swing.JPanel {
    
    
    public PanelPhase2_0() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textA_SPA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        ct = new javax.swing.JLabel();
        textA_CT = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        textA_P = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        textA_L = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        textA_S = new javax.swing.JTextArea();
        bg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 540));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(12, 120, 73));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SPA (Sales Process Analyser)");
        add(jLabel1);
        jLabel1.setBounds(310, 50, 280, 30);

        textA_SPA.setColumns(20);
        textA_SPA.setEditable(false);
        textA_SPA.setFont(new java.awt.Font("Tahoma", 1, 15));
        textA_SPA.setRows(5);
        textA_SPA.setText("Sales Process Analyser is a sales management tool that enables you to identify weak areas in your sales\n                      process and have more qualified prospects, leads and more sales conversions.");
        textA_SPA.setOpaque(false);
        add(textA_SPA);
        textA_SPA.setBounds(60, 90, 780, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CT (Clients Touched)");
        add(jLabel2);
        jLabel2.setBounds(50, 295, 162, 20);

        ct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Defination/CT.png"))); // NOI18N
        ct.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(ct);
        ct.setBounds(50, 185, 162, 101);

        textA_CT.setColumns(20);
        textA_CT.setEditable(false);
        textA_CT.setFont(new java.awt.Font("Tahoma", 0, 12));
        textA_CT.setRows(5);
        textA_CT.setText("All customers touched by \nyou through a direct \ncommunication like : Phone\nCall, Mailer, E-Mailer, \nEvent.");
        textA_CT.setOpaque(false);
        add(textA_CT);
        textA_CT.setBounds(50, 320, 162, 110);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("P (Prospects)");
        add(jLabel3);
        jLabel3.setBounds(262, 295, 162, 20);

        p.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Defination/P.png"))); // NOI18N
        p.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(p);
        p.setBounds(262, 185, 162, 101);

        textA_P.setColumns(20);
        textA_P.setEditable(false);
        textA_P.setFont(new java.awt.Font("Tahoma", 0, 12));
        textA_P.setRows(5);
        textA_P.setText("All customers who after first \ntouch have shown interest in your products, \nsolutions and services and \nhave given you an \nopportunity to gauge their \nneed.");
        textA_P.setOpaque(false);
        add(textA_P);
        textA_P.setBounds(262, 320, 162, 110);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("L (Leads)");
        add(jLabel4);
        jLabel4.setBounds(474, 295, 162, 20);

        l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Defination/L.png"))); // NOI18N
        l.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(l);
        l.setBounds(474, 185, 162, 101);

        textA_L.setColumns(20);
        textA_L.setEditable(false);
        textA_L.setFont(new java.awt.Font("Tahoma", 0, 12));
        textA_L.setRows(5);
        textA_L.setText("All customers who have \nengaged with you to give \nyou a chance of sale, based \non identification of a \nrequirement and requested \nfor a solution, product or a \nservice quote.");
        textA_L.setOpaque(false);
        add(textA_L);
        textA_L.setBounds(474, 320, 162, 110);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("S (Sales)");
        add(jLabel5);
        jLabel5.setBounds(686, 295, 162, 20);

        s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        s.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Defination/S.png"))); // NOI18N
        s.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(s);
        s.setBounds(686, 185, 162, 101);

        textA_S.setColumns(20);
        textA_S.setEditable(false);
        textA_S.setFont(new java.awt.Font("Tahoma", 0, 12));
        textA_S.setRows(5);
        textA_S.setText("All customers who have \nnegotiated on terms & \nconditions and given you a \nPurchase Order with \nPayment.");
        textA_S.setOpaque(false);
        add(textA_S);
        textA_S.setBounds(686, 320, 162, 110);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents
 
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel ct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l;
    private javax.swing.JLabel p;
    private javax.swing.JLabel s;
    private javax.swing.JTextArea textA_CT;
    private javax.swing.JTextArea textA_L;
    private javax.swing.JTextArea textA_P;
    private javax.swing.JTextArea textA_S;
    private javax.swing.JTextArea textA_SPA;
    // End of variables declaration//GEN-END:variables
}
