/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPhase5.java
 *
 * Created on Feb 28, 2012, 10:02:45 PM
 */
package salesPackage;

/**
 *
 * @author user
 */
public class PanelPhase5 extends javax.swing.JPanel {

    /** Creates new form PanelPhase5 */
    public PanelPhase5() {
        initComponents();
    }
    public int p5_r1;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Gp_p5_q1 = new javax.swing.ButtonGroup();
        heading_p5 = new javax.swing.JLabel();
        label_p5_q1 = new javax.swing.JLabel();
        radio_p5_q1_1 = new javax.swing.JRadioButton();
        radio_p5_q1_2 = new javax.swing.JRadioButton();
        radio_p5_q1_3 = new javax.swing.JRadioButton();
        radio_p5_q1_4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        diagram = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(900, 540));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(900, 540));
        setLayout(null);

        heading_p5.setFont(new java.awt.Font("Tahoma", 1, 16));
        heading_p5.setForeground(new java.awt.Color(12, 120, 73));
        heading_p5.setText("5. Generate Sales:");
        add(heading_p5);
        heading_p5.setBounds(20, 200, 160, 20);

        label_p5_q1.setFont(new java.awt.Font("Tahoma", 1, 12));
        label_p5_q1.setText("Q1) Do you have product/solution/services presentations to be exhibited to Technical Buyer, Strategic Buyer");
        add(label_p5_q1);
        label_p5_q1.setBounds(30, 250, 710, 20);

        btn_Gp_p5_q1.add(radio_p5_q1_1);
        radio_p5_q1_1.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p5_q1_1.setText("Yes we have presentations to exihibit our product/solutions/services to our accounts in Strategic / Technical / Economic mode of evaluation.");
        radio_p5_q1_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p5_q1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p5_q1_1.setOpaque(false);
        radio_p5_q1_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p5_q1_1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p5_q1_1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p5_q1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p5_q1_1ActionPerformed(evt);
            }
        });
        add(radio_p5_q1_1);
        radio_p5_q1_1.setBounds(47, 355, 805, 27);

        btn_Gp_p5_q1.add(radio_p5_q1_2);
        radio_p5_q1_2.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p5_q1_2.setText("Yes we have presentations but they are all combined. ");
        radio_p5_q1_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p5_q1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p5_q1_2.setOpaque(false);
        radio_p5_q1_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p5_q1_2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p5_q1_2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p5_q1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p5_q1_2ActionPerformed(evt);
            }
        });
        add(radio_p5_q1_2);
        radio_p5_q1_2.setBounds(47, 380, 805, 27);

        btn_Gp_p5_q1.add(radio_p5_q1_3);
        radio_p5_q1_3.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p5_q1_3.setText("Yes we have presentations but they are not made according to Strategic, Technical and Economic Buying Evaluation.");
        radio_p5_q1_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p5_q1_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p5_q1_3.setOpaque(false);
        radio_p5_q1_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p5_q1_3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p5_q1_3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p5_q1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p5_q1_3ActionPerformed(evt);
            }
        });
        add(radio_p5_q1_3);
        radio_p5_q1_3.setBounds(47, 405, 805, 27);

        btn_Gp_p5_q1.add(radio_p5_q1_4);
        radio_p5_q1_4.setFont(new java.awt.Font("Tahoma", 0, 12));
        radio_p5_q1_4.setText("No we do not have presentations. ");
        radio_p5_q1_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_p5_q1_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_1.gif"))); // NOI18N
        radio_p5_q1_4.setOpaque(false);
        radio_p5_q1_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_2.gif"))); // NOI18N
        radio_p5_q1_4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_4.gif"))); // NOI18N
        radio_p5_q1_4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Radio_button_3.gif"))); // NOI18N
        radio_p5_q1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_p5_q1_4ActionPerformed(evt);
            }
        });
        add(radio_p5_q1_4);
        radio_p5_q1_4.setBounds(47, 430, 805, 27);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("• Strategic Buyer:");
        add(jLabel1);
        jLabel1.setBounds(60, 290, 120, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("• Technical Buyer:");
        add(jLabel2);
        jLabel2.setBounds(60, 310, 120, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("• Economic Buyer:  ");
        add(jLabel3);
        jLabel3.setBounds(240, 290, 130, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("• Joint: ");
        add(jLabel4);
        jLabel4.setBounds(240, 310, 70, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText(" & Economic Buyer – Separate and Joint? (yes / no) ");
        add(jLabel5);
        jLabel5.setBounds(50, 270, 370, 15);

        diagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/SPDiag_5_1.gif"))); // NOI18N
        add(diagram);
        diagram.setBounds(155, 20, 590, 170);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/panel_bg_trans.png"))); // NOI18N
        bg.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(bg);
        bg.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void radio_p5_q1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p5_q1_1ActionPerformed
        // TODO add your handling code here:
        p5_r1=1;
    }//GEN-LAST:event_radio_p5_q1_1ActionPerformed

    private void radio_p5_q1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p5_q1_2ActionPerformed
        // TODO add your handling code here:
        p5_r1=2;
    }//GEN-LAST:event_radio_p5_q1_2ActionPerformed

    private void radio_p5_q1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p5_q1_3ActionPerformed
        // TODO add your handling code here:
        p5_r1=3;
    }//GEN-LAST:event_radio_p5_q1_3ActionPerformed

    private void radio_p5_q1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_p5_q1_4ActionPerformed
        // TODO add your handling code here:
        p5_r1=4;
    }//GEN-LAST:event_radio_p5_q1_4ActionPerformed

    //----------------------- MyMethods-----------------------
    public boolean assignAllData(Record ref)
    {
        String errMsg="Please select an option!";                      
                
        try
        {
            if(p5_r1==0)
                { throw new Exception(errMsg); }
            else
                { 
                    ref.phase5[0]=p5_r1;
                }                                      
        }catch(Exception e)
        {
            //System.out.println(e.getMessage());
            SPA.panelController(e.getMessage(), new int[]{2,0,1,3,1,0});
            return(false);
        }
        
        SPA.panelController(null, new int[]{0,0,0,3,1,0});
        return(true);
    }
    
    void resetPanel()
    {
        p5_r1=0;
        btn_Gp_p5_q1.clearSelection();      
    }
    
    
    void loadPanel(Record r)
    {           
        p5_r1=r.phase5[0];        
        
        switch(r.phase5[0]) 
        {
            case 1 : radio_p5_q1_1.setSelected(true); break;
            case 2 : radio_p5_q1_2.setSelected(true); break;
            case 3 : radio_p5_q1_3.setSelected(true); break;
            case 4 : radio_p5_q1_4.setSelected(true); break;                                
        }       
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup btn_Gp_p5_q1;
    private javax.swing.JLabel diagram;
    private javax.swing.JLabel heading_p5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label_p5_q1;
    private javax.swing.JRadioButton radio_p5_q1_1;
    private javax.swing.JRadioButton radio_p5_q1_2;
    private javax.swing.JRadioButton radio_p5_q1_3;
    private javax.swing.JRadioButton radio_p5_q1_4;
    // End of variables declaration//GEN-END:variables
}
