/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

import javax.swing.JWindow;
import javax.swing.UIManager;

/**
 *
 * @author Gagandeep
 */
public class SPALoader extends javax.swing.JWindow {

    static LogHandler log =new LogHandler();
    
    static Diagnostic diagnose =new Diagnostic();   
    
        
    public SPALoader() 
    {
        try{
              UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
          }catch(Exception e)
          {  System.out.println("Windows isn't available"); }
        
        initComponents();
        
        this.setLocationRelativeTo(null);    
        
        log.writeToLog(11);
                       
    }
    
    
    public static void main( String args[] )  
    {  
        
        Thread t = Thread.currentThread();        
        
        
        SPALoader loader= new SPALoader();
        loader.setVisible( true );
        
        try{
            t.sleep(2000);            
        }catch(InterruptedException e)
        {}
        
        BG_1.setVisible(false);
        System.out.println("Starting now");
               
        log.writeToLog(12);
        try{
            t.sleep(1000);            
        }catch(InterruptedException e)
        {}
        
        //(1)
        diagnose.identifyProblem();
        if(diagnose.dbFlag>1)
        { diagnose.db.checkReadOnly(true); }
        
        if( (diagnose.configFlag==1 || diagnose.configFlag==0) && (diagnose.dbFlag<1 || diagnose.logFlag!=34 || diagnose.formateFlag!=1))
        { Dialog_diagnosResult d =new Dialog_diagnosResult(null, true);
          d.getStates(diagnose);
          d.setVisible(true);
        }
        
        //(2)
        if(diagnose.configFlag!=1 || diagnose.dbFlag<1 || diagnose.logFlag!=1 || diagnose.backupFlag!=1 || diagnose.formateFlag!=1)            
        {  diagnose.resolveProblems();  }
        
        log.writeToLog(31);
        //(3)
        SPA app=new SPA();
        app.MAXRID=diagnose.dbFlag;   //Pass Max record to SPA
        app.DB=diagnose.db;           //pass the database settings to spa
        SPA.DIAGNOSE=diagnose;        //Pass diagnose results
        SPA.CNF=diagnose.cnf;         //pass conf 
        //System.out.println(SPA.CNF.firstName);
        //app.DB.dataSourceName=diagnose.db.dataSourceName;   //pass the database setting to spa
        
        bar(100);    
        
        app.setVisible(true);        
        loader.dispose();
        
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_close = new javax.swing.JButton();
        BG_1 = new javax.swing.JLabel();
        lbl_load = new javax.swing.JLabel();
        pbar_trans = new javax.swing.JLabel();
        pbar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_cmp = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        BG = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setMinimumSize(new java.awt.Dimension(450, 300));
        getContentPane().setLayout(null);

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/bbl_close_1.png"))); // NOI18N
        btn_close.setBorderPainted(false);
        btn_close.setContentAreaFilled(false);
        btn_close.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/bbl_close_3.png"))); // NOI18N
        btn_close.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Bubble/bbl_close_2.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close);
        btn_close.setBounds(400, 10, 40, 27);

        BG_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/UAE.png"))); // NOI18N
        BG_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(BG_1);
        BG_1.setBounds(0, 0, 450, 300);

        lbl_load.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_load.setForeground(new java.awt.Color(0, 102, 0));
        lbl_load.setText("Starting SPA...");
        getContentPane().add(lbl_load);
        lbl_load.setBounds(20, 177, 140, 13);

        pbar_trans.setBackground(new java.awt.Color(232, 75, 75));
        pbar_trans.setOpaque(true);
        getContentPane().add(pbar_trans);
        pbar_trans.setBounds(20, 195, 8, 2);

        pbar.setBackground(new java.awt.Color(193, 2, 2));
        pbar.setOpaque(true);
        getContentPane().add(pbar);
        pbar.setBounds(20, 195, 8, 5);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Registered to :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 210, 70, 13);

        lbl_name.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(lbl_name);
        lbl_name.setBounds(20, 225, 250, 14);

        lbl_cmp.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_cmp.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(lbl_cmp);
        lbl_cmp.setBounds(20, 240, 250, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("© 2012 United Avenir Engineers\nsingh.gagan144@gmail.com | 9717568636");
        jTextArea1.setOpaque(false);
        getContentPane().add(jTextArea1);
        jTextArea1.setBounds(20, 260, 325, 30);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salesPackage/Images/Loader_BG.png"))); // NOI18N
        BG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(BG);
        BG.setBounds(0, 0, 450, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:                
        dispose();
        System.exit(0);
        // load();
    }//GEN-LAST:event_btn_closeActionPerformed

    static void bar(int n)
    {
        pbar.setSize(n*4, 5);
        pbar_trans.setSize(n*4, 2);
        
        if(n<44)
        {   lbl_load.setText("Scanning system..."); }
        else if(n>44 && n<88)
        {   lbl_load.setText("Running Diagnostic..."); }
        else
        {   lbl_load.setText("Preparing to start..."); }
    }
    
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private static javax.swing.JLabel BG_1;
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JLabel lbl_cmp;
    private static javax.swing.JLabel lbl_load;
    public static javax.swing.JLabel lbl_name;
    private static javax.swing.JLabel pbar;
    private static javax.swing.JLabel pbar_trans;
    // End of variables declaration//GEN-END:variables
}
