/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package salesPackage;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Gagandeep
 */
public class Tool extends javax.swing.JFrame {

    /**
     * Creates new form Tool
     */
        
    
    Configuration CNF = new Configuration();
    DatabaseHandler DB = new DatabaseHandler();
    StrageticData userData;
    
    
    public Tool() 
    { 
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }catch(Exception e)
        {  System.out.println("Windows isn't available"); }
        
        userData=new StrageticData();
        
        userData.r.recordID=999;//-------------------------DELETE
        
        initComponents();  
          DB.dataSourceName="SalesToolDB"; 
          
          this.addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent e) {
                // This is only called when the user releases the mouse button.
                Dimension d= getSize();
                if (d.width> 1024 || d.height> 720)
                     setSize(1024,720);
            }
        });
          
        
        //Send Referneces to Panels
          panelMineData1.getReferences(DB);
        //panel_GettingStarted2.getReferences(DB, CNF);
          panel_GettingStarted2.getReferences(new DatabaseHandler(), new Configuration());
        panel_login1.getReference(CNF);
        
         ///----DELETE        
        panelMineData1.setVisible(false);
        panelOutput_graph21.setVisible(false);
        panel_GettingStarted2.setVisible(false);
        panel_login1.setVisible(false);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Save1 = new salesPackage.Panel_Save();
        panelMineData1 = new salesPackage.PanelMineData();
        panelOutput_graph21 = new salesPackage.PanelOutput_graph2();
        panel_login1 = new salesPackage.Panel_login();
        panel_GettingStarted2 = new salesPackage.Panel_GettingStarted();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Analyse Tool");
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusCycleRoot(false);
        setForeground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1024, 720));
        setMinimumSize(new java.awt.Dimension(800, 570));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                something(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(panel_Save1);
        panel_Save1.setBounds(20, 30, 900, 540);
        getContentPane().add(panelMineData1);
        panelMineData1.setBounds(20, 20, 900, 540);
        getContentPane().add(panelOutput_graph21);
        panelOutput_graph21.setBounds(20, 90, 900, 540);
        getContentPane().add(panel_login1);
        panel_login1.setBounds(10, 20, 900, 540);
        getContentPane().add(panel_GettingStarted2);
        panel_GettingStarted2.setBounds(40, 60, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void something(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_something
        // TODO add your handling code here:
        System.out.println("Byee");
    }//GEN-LAST:event_something
    

    public String getCurrentCard(JPanel parent)
    {
         JPanel card = null;
         String name="";

         for (Component comp : parent.getComponents() ) 
         {
            if (comp.isVisible() == true) 
            {
                card = (JPanel)comp;
                name=card.getName();
                //System.out.println(card.getName() );
            }
         }   
    
         return(name);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Tool().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private salesPackage.PanelMineData panelMineData1;
    private salesPackage.PanelOutput_graph2 panelOutput_graph21;
    private salesPackage.Panel_GettingStarted panel_GettingStarted2;
    private salesPackage.Panel_Save panel_Save1;
    private salesPackage.Panel_login panel_login1;
    // End of variables declaration//GEN-END:variables
}
